### ISSUE TITLE
gradle spring-boot plugin 1.3.0.M1 does not work with gradle 2.5-rc-1

### ISSUE THREAD

**Issue by mxab** [spring-projects/spring-boot#3334]
Hi,
if I use gradle 2.5-rc-1 and spring-boot 1.3.0.M1 it get following error:

```
Caused by: java.lang.NoClassDefFoundError: org/gradle/mvn3/org/apache/maven/model/building/ModelBuildingException
	at io.spring.gradle.dependencymanagement.DependencyManagementPlugin.class$(DependencyManagementPlugin.groovy)
	at io.spring.gradle.dependencymanagement.DependencyManagementPlugin.$get$$class$io$spring$gradle$dependencymanagement$maven$EffectiveModelBuilder(DependencyManagementPlugin.groovy)
	at io.spring.gradle.dependencymanagement.DependencyManagementPlugin.apply(DependencyManagementPlugin.groovy:79)
	at io.spring.gradle.dependencymanagement.DependencyManagementPlugin.apply(DependencyManagementPlugin.groovy)
	at org.gradle.api.internal.plugins.ImperativeOnlyPluginApplicator.applyImperative(ImperativeOnlyPluginApplicator.java:35)
	at org.gradle.api.internal.plugins.RuleBasedPluginApplicator.applyImperative(RuleBasedPluginApplicator.java:43)
	at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:144)
	at org.gradle.api.internal.plugins.DefaultPluginManager.addImperativePlugin(DefaultPluginManager.java:67)
	at org.gradle.api.internal.plugins.DefaultPluginManager.addImperativePlugin(DefaultPluginManager.java:73)
	at org.gradle.api.internal.plugins.DefaultPluginContainer.apply(DefaultPluginContainer.java:60)
	at org.gradle.api.plugins.PluginContainer$apply$0.call(Unknown Source)
	at org.springframework.boot.gradle.dependencymanagement.DependencyManagementPluginFeatures.apply(DependencyManagementPluginFeatures.groovy:34)
	at org.springframework.boot.gradle.PluginFeatures$apply$0.call(Unknown Source)
	at org.springframework.boot.gradle.SpringBootPlugin.apply(SpringBootPlugin.groovy:49)
	at org.springframework.boot.gradle.SpringBootPlugin.apply(SpringBootPlugin.groovy)
...
...
	... 50 more
Caused by: java.lang.ClassNotFoundException: org.gradle.mvn3.org.apache.maven.model.building.ModelBuildingException
	... 79 more
```

it works with spring boot 1.2.4.RELEASE

**Comment by wilkinsona** [comment]
Looks like they've (re)moved the repackaged Maven classes. This'll need to be fixed in the dependency management plugin. Until then, Gradle 2.4 should work with Boot 1.3
