### ISSUE TITLE
NoSuchMethodError when using SnakeYAML 2.0

### ISSUE THREAD

**Issue by dVenkatNaveen** [spring-projects/spring-boot#34527]
When I upgrade snakeyaml from 1.33 to 2.0 version.
snakeyaml dependency
<dependency>
    <groupId>org.yaml</groupId>
    <artifactId>snakeyaml</artifactId>
    <version>2.0</version>
</dependency>

Error log
Exception in thread "main" java.lang.NoSuchMethodError: org.yaml.snakeyaml.parser.ParserImpl.<init>(Lorg/yaml/snakeyaml/reader/StreamReader;)V
	at com.fasterxml.jackson.dataformat.yaml.YAMLParser.<init>(YAMLParser.java:159)
	at com.fasterxml.jackson.dataformat.yaml.YAMLFactory._createParser(YAMLFactory.java:455)
	at com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:357)
	at org.elasticsearch.common.xcontent.yaml.YamlXContent.createParser(YamlXContent.java:84)
	at org.elasticsearch.common.settings.Settings$Builder.loadFromStream(Settings.java:1103)
	at org.elasticsearch.common.settings.Settings$Builder.loadFromPath(Settings.java:1086)
	at org.elasticsearch.node.InternalSettingsPreparer.prepareEnvironment(InternalSettingsPreparer.java:83)
	at org.elasticsearch.cli.EnvironmentAwareCommand.createEnv(EnvironmentAwareCommand.java:100)
	at org.elasticsearch.cli.EnvironmentAwareCommand.createEnv(EnvironmentAwareCommand.java:91)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:126)
	at org.elasticsearch.bootstrap.ElasticsearchAdapter.start(ElasticsearchAdapter.java:62)
	at org.elasticsearch.bootstrap.ElasticsearchAdapter.main(ElasticsearchAdapter.java:172)

**Comment by juan91** [comment]
Iam using the following dependencies:

implementation group: 'org.yaml', name: 'snakeyaml', version: '2.0'
implementation group: 'com.fasterxml.jackson.core', name: 'jackson-databind', version: '2.15.0'

and I get the following error:
Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

     com.fasterxml.jackson.dataformat.yaml.YAMLParser.<init>(YAMLParser.java:178)

Correct the classpath of your application so that it contains compatible versions of the classes com.fasterxml.jackson.dataformat.yaml.YAMLParser and org.yaml.snakeyaml.parser.Pars
erImpl

Is there a solution to the previous error?

**Comment by wilkinsona** [comment]
@juan91 this is no different to the situation above. Perhaps something else in your build means that you aren't actually using Jackson 2.15? It's impossible to tell from two dependency declarations alone. I would use a build scan or `gradle dependencies` to double-check. If you have any further questions, please follow up on Stack Overflow or [Gitter](https://gitter.im/spring-projects/spring-boot). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/main/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.

**Comment by Zgy0806** [comment]
@juan91 try this    
<dependency>
            <groupId>com.fasterxml.jackson.dataformat</groupId>
            <artifactId>jackson-dataformat-yaml</artifactId>
            <version>2.15.0</version>
        </dependency>
