### ISSUE TITLE
[bug] Possible regression with SB 3.2.3 and Spring Data Couchbase

### ISSUE THREAD

**Issue by juliojgd** [spring-projects/spring-boot#39740]
We use Spring Boot 3.2.2 in our application and when upgrading to 3.2.3 we found this **compilation** error:
```
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] Bad service configuration file, or exception thrown while constructing Processor object: com/querydsl/apt/Abs>
[INFO] 1 error
```
It's trivial to reproduce, generate a project with SB 3.2.3 and Spring Data Couchbase from Initializr and `mvn clean install' it.

 I attach a zip with the reproducer.
[sbcouchbaseregression.zip](https://github.com/spring-projects/spring-boot/files/14384834/sbcouchbaseregression.zip)

See also [the report](http://disq.us/p/2xt0jq5) by [Christopher Abbonizio](https://disqus.com/by/christopherabbonizio/) at the blog post.

**Comment by wilkinsona** [comment]
This regression is caused by [this change](https://github.com/spring-projects/spring-data-couchbase/commit/86713c527c0e6cf5a3fde6fa44f119cc719c9bb9) in Spring Data Couchbase. Please open a [Spring Data Couchbase issue](https://github.com/spring-projects/spring-data-couchbase/issues) so that it can be addressed.


In the meantime, you can work around it by adding a dependency on `querydsl-apt`:

```xml
<dependency>
    <groupId>com.querydsl</groupId>
    <artifactId>querydsl-apt</artifactId>
</dependency>
```

Another option may be to configure Maven's compiler plugin to disable annotation processing or to only run certain processors. I don't think Gradle users will be affected as Gradle does not use the compile classpath for annotation processor discovery.

**Comment by cabbonizio** [comment]
Hi all, Mike Reiche from spring data couchbase already put in a fix for this yesterday.   I'm not at my computer but will post a link to the issue so things can be linked.

**Comment by cabbonizio** [comment]
Here's the PR I believe that will fix this:

https://github.com/spring-projects/spring-data-couchbase/pull/1908

**Comment by juliojgd** [comment]
> Here's the PR I believe that will fix this:
> 
> [spring-projects/spring-data-couchbase#1908](https://github.com/spring-projects/spring-data-couchbase/pull/1908)

Are you sure? I can't find the relation between https://github.com/spring-projects/spring-data-couchbase/pull/1908 and this problem.

**Comment by cabbonizio** [comment]
@juliojgd this is what I heard from Mike Reiche yesterday, but I think it's good you opened that issue on Spring Data Couchbase side to spread the awareness.
