### ISSUE TITLE
spring boot json tester does not work with assertj 3.9.1

### ISSUE THREAD

**Issue by tsachev** [spring-projects/spring-boot#12224]
assertj `JsonContent`  assertion provider does not seem to work with 3.9.1

```
java.lang.NoSuchMethodError: org.assertj.core.api.Assertions.assertThat(Ljava/lang/Object;)Lorg/assertj/core/api/AbstractObjectAssert;

	at org.springframework.boot.test.json.JsonContentAssert.extractingJsonPathValue(JsonContentAssert.java:899)
	at com.example.assertjissue.AssertJIssueApplicationTests.contextLoads(AssertJIssueApplicationTests.java:13)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

```

Here is my test case

```
package com.example.assertjissue;

import org.assertj.core.api.Assertions;
import org.junit.Test;
import org.springframework.boot.test.json.BasicJsonTester;
import org.springframework.boot.test.json.JsonContent;

public class AssertJIssueApplicationTests {
    private final BasicJsonTester json = new BasicJsonTester(AssertJIssueApplicationTests.class);
    @Test
    public void contextLoads() {
        JsonContent<Object> content = this.json.from("{\"key\": \"value\"}");
        Assertions.assertThat(content).extractingJsonPathValue("key").isEqualTo("value");
    }
}
```

Tested with both spring-boot `1.5.10.RELEASE` and `2.0.0.RC2`

**Comment by wilkinsona** [comment]
This is due to a [binary incompatible change](https://github.com/joel-costigliola/assertj-core/commit/fabeac7a2beb73497acdd61fdb446debb8fdbe01) in AssertJ 3.9.1. We can (and should) upgrade to 3.9.1 in 2.0.0. Spring Boot 1.5 uses AssertJ 2.6 by default. There's been no equivalent breaking change in AssertJ 2.x as far as I can see, so I don't think we should do anything in 1.5 and AssertJ 2.x should be used as recommended by Boot's dependency management.
