### ISSUE TITLE
Upgrading from 3.1.5 to 3.2.0 gives NoClassDefFoundError: javax/xml/bind/annotation/XmlElement

### ISSUE THREAD

**Issue by Polve** [spring-projects/spring-boot#38516]
I'm trying to upgrade to latest version of spring boot (just released) and while the program compiles correctly it does not run anymore giving a class not found error:

> Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlElement
        at com.fasterxml.jackson.module.jaxb.JaxbAnnotationIntrospector.<init>(JaxbAnnotationIntrospector.java:137) ~[jackson-module-jaxb-annotations-2.15.3.jar:2.15.3]

I'm using OpenJDK 21

I checked carefully all the release notes and I was not able to find anything related to that problem and the changes needed to correct the dependency problem: did I overlooked something?

**Comment by wilkinsona** [comment]
You appear to be using the wrong Jackson module. You need `jackson-module-jakarta-xmlbind-annotations` rather than `jackson-module-jaxb-annotations` that you appear to be using. This has been the case since Jackson 2.13 when the jakarta module was introduced so I'm not sure why it would only come to light when upgrading from Spring Boot 3.1 to 3.2. 

Can you share a minimal reproducer that works with 3.1 but fails when upgraded to 3.2?

**Comment by Polve** [comment]
For the moment it's too complex to give a minimal reproduction case, but in my pom.xml I have no direct reference to jackson because it gets pulled in (I suppose) by some boot modules.

I can share my spring boot dependencies:

```
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-jpa</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-aop</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-websocket</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-mail</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>org.springframework.retry</groupId>
      <artifactId>spring-retry</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-security</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.security</groupId>
      <artifactId>spring-security-messaging</artifactId>
    </dependency>

```

**Comment by Grey1024** [comment]
I am a Java backend programmer from China, and I have lost my job. Now, I am looking for a coding job outside of China, and I don’t mind the salary. I am even willing to work for free. Additionally, I hope to improve my English communication skills. If you need my help, please contact me at [jeeun2023@outlook.com](mailto:jeeun2023@outlook.com).
I just want to find something to do; I love programming. If you have the patience to explain your work tasks to someone whose English is not good, I am willing to work for you without caring about payment.

**Comment by Polve** [comment]
I'm sorry I didn't know how to build dependency tree, thanks :-P

So the problem seems to be that the library is pulled in by another dependency: org.glassfish.jersey.media:jersey-media-json-jackson:jar:3.1.3:compile

I will try to exclude it and replace with the one you mentioned.

Thanks
