### ISSUE TITLE
Version 2.1.7 not compatible with elasticsearch 5.6.7

### ISSUE THREAD

**Issue by mrkk** [spring-projects/spring-boot#18259]
Looks like new code is not compatible with old clients

I see

```
[ERROR] [org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet].log:175]- Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: org.elasticsearch.client.Request.<init>(Ljava/lang/String;Ljava/lang/String;)V] with root cause java.lang.NoSuchMethodError: org.elasticsearch.client.Request.<init>(Ljava/lang/String;Ljava/lang/String;)V
 at org.springframework.boot.actuate.elasticsearch.ElasticsearchRestHealthIndicator.doHealthCheck(ElasticsearchRestHealthIndicator.java:60)
```

**Comment by wilkinsona** [comment]
Spring Boot 2.1.7 is [built and tested against Elasticsearch 6.4.3](https://github.com/spring-projects/spring-boot/blob/faa435459b83b1b47db8bfe4b6bdd0a949aef831/spring-boot-project/spring-boot-dependencies/pom.xml#L64). Unfortunately, we cannot maintain backwards compatibility with a previous major version, particularly one that [has reached end of life](https://www.elastic.co/support/eol). If 2.1.x worked in the past with 5.6.x then I am afraid this was by luck rather than design and cannot be relied upon.

If you're not in a position to upgrade to Elasticsearch 6.4.x, you can disable the health indicator with the following configuration:

```
management.health.elasticsearch.enabled = false
```
