### ISSUE TITLE
Gradle 4.0 Build Causes java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by jsicotte** [spring-projects/spring-boot#9600]
It seems that multi-project builds may break when upgrading to Gradle 4.0. I have provided a sample project [here](https://github.com/jsicotte/gradleissue). When `./gradlew --stacktrace build` is run, the build will fail with the following error (some lines removed for brevity):

```
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':projectB:bootRepackage'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)

Caused by: java.lang.NoSuchMethodError: org.gradle.api.artifacts.ProjectDependency.getConfiguration()Ljava/lang/String;
        at org.springframework.boot.gradle.repackage.ProjectLibraries.getLibrariesForFileDependencies(ProjectLibraries.java:132)
        at org.springframework.boot.gradle.repackage.ProjectLibraries.getLibraries(ProjectLibraries.java:113)

BUILD FAILED in 1s
```
I have only experienced the `NoSuchMethodError` when dealing with multi-project builds, everything works fine once I remove the dependancy:

```
--- a/projectB/build.gradle
+++ b/projectB/build.gradle
@@ -7,5 +7,4 @@ dependencies {
         exclude module: "spring-boot-starter-tomcat"
     }
     compile("org.springframework.boot:spring-boot-starter-jetty")
-    compile project(':projectA')
 }
```

**Comment by iyossi** [comment]
Hi
I have the same problem . After upgrading from gradle 3.4.1 to 4.0 with multi-project build.

**Comment by wilkinsona** [comment]
Duplicates #8154

**Comment by iyossi** [comment]
Hi,

Why do think it is duplicate of #8154 ? my case is about a problem that is
new in gradle 4.0 and didn't happen in previous versions, while #8154 is
about gradle 3.3 (where I don't have a problem) .
Additionally , that case is abotu a deprecation warning, while mine is
about a build failure.

Regards,
Yossi

**Comment by wilkinsona** [comment]
@lyossi You said that you have the same problem as @jsicotte. @jsicotte was using Spring Boot 1.5.1 with Gradle 4.0. #8154, which was fixed in Spring Boot 1.5.2, replaced the usage of a Gradle API that was deprecated in 3.3 and removed in 4.0.

**Comment by gigenthomas** [comment]
I am running into the same issue after upgrading to Gradle 4 , with spring-boot 1.5.4

**Comment by wilkinsona** [comment]
@gigenthomas If that is the case, please open a new issue with a sample project that reproduces the problem.
