### ISSUE TITLE
Metrics endpoint in Spring boot 2 not working with Micrometer core 1.0.0-rc.4

### ISSUE THREAD

**Issue by rohitrajt** [spring-projects/spring-boot#11336]
With Spring Boot 2.0.0.M6 if we start using micrometer-core 1.0.0-rc.4 or 1.0.0-rc.5, the metrics endpoints fails with the below exception,

invoking with url: `http://localhost:8080/application/metrics`
```
Caused by: java.lang.NoSuchMethodError: io.micrometer.core.instrument.MeterRegistry.getMeters()Ljava/util/Collection;
	at org.springframework.boot.actuate.metrics.MetricsEndpoint.collectNames(MetricsEndpoint.java:71) ~[spring-boot-actuator-2.0.0.M6.jar:2.0.0.M6]
	at org.springframework.boot.actuate.metrics.MetricsEndpoint.lambda$collectNames$0(MetricsEndpoint.java:68) ~[spring-boot-actuator-2.0.0.M6.jar:2.0.0.M6]
	at java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4649) ~[na:1.8.0_102]
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1080) ~[na:1.8.0_102]
	at org.springframework.boot.actuate.metrics.MetricsEndpoint.collectNames(MetricsEndpoint.java:68) ~[spring-boot-actuator-2.0.0.M6.jar:2.0.0.M6]
	at org.springframework.boot.actuate.metrics.MetricsEndpoint.listNames(MetricsEndpoint.java:61) ~[spring-boot-actuator-2.0.0.M6.jar:2.0.0.M6]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_102]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_102]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_102]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_102]
	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:223) ~[spring-core-5.0.1.RELEASE.jar:5.0.1.RELEASE]
	at org.springframework.boot.actuate.endpoint.ReflectiveOperationInvoker.invoke(ReflectiveOperationInvoker.java:130) ~[spring-boot-actuator-2.0.0.M6.jar:2.0.0.M6]
	at org.springframework.boot.actuate.endpoint.web.servlet.WebMvcEndpointHandlerMapping$OperationHandler.handle(WebMvcEndpointHandlerMapping.java:133) ~[spring-boot-actuator-2.0.0.M6.jar:2.0.0.M6]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_102]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_102]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_102]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_102]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209) ~[commons-spring-2.0.3-SNAPSHOT.jar:na]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136) ~[commons-spring-2.0.3-SNAPSHOT.jar:na]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102) ~[spring-webmvc-5.0.1.RELEASE.jar:5.0.1.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:871) ~[spring-webmvc-5.0.1.RELEASE.jar:5.0.1.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:777) ~[spring-webmvc-5.0.1.RELEASE.jar:5.0.1.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.0.1.RELEASE.jar:5.0.1.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991) ~[spring-webmvc-5.0.1.RELEASE.jar:5.0.1.RELEASE]
	... 52 common frames omitted
```

I see that `MeterRegistry.getMeters` has been changed to return a `List<Meter>` instead of `Collection<Meter>` in 1.0.0-rc.4 (https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-core/src/main/java/io/micrometer/core/instrument/MeterRegistry.java#L156)

**Comment by bclozel** [comment]
This is why `2.0.0.M6` depends on Micrometer `1.0.0-rc.3`. Micrometer is not yet GA, so API changes are still expected.

Why do you specifically need Micrometer `1.0.0-rc.4` or `1.0.0-rc.5`?
Why not using Spring Boot `2.0.0.M7` in that case?

I'm closing this for now as the behaviour you're describing is expected.

**Comment by rohitrajt** [comment]
@bclozel Thanks for the explanation. Sorry I missed that. 

I am using `1.0.0-rc.4` or `1.0.0-rc.5` to get the hystrix metrics publisher support built in micrometer.

I will try with `2.0.0.M7` and update this issue.
