### ISSUE TITLE
gradle bom support not working with boot 2.0.1

### ISSUE THREAD

**Issue by dyroberts** [spring-projects/spring-boot#12793]
When using gradle to build a new boot app, instead of using the spring `dependency-management-plugin`, you can use gradle's native bom support. 

See the gradle docs here: https://docs.gradle.org/4.6/userguide/managing_transitive_dependencies.html#sec:bom_import
They even use `spring-boot-dependencies` as their example bom!

This works great with boot version 2.0.0.RELEASE and below. However, with 2.0.1.RELEASE it breaks!
Seems to be a dependency version conflict between boot 2.0.1 and beans 5.0.5 on org.yaml:snakeyaml

I've created a sample app to expose the issue:
https://github.com/pivotal-dylan-roberts/boot-2.0.1-bom-gradle

The sample was created with initializr, adding just the web starter dependency.
I then removed the `dependency-management-plugin` and added the `enableFeaturePreview('IMPROVED_POM_SUPPORT')` line in settings.gradle and the bom dependency, of course.

You'll see that the default `contextLoads` test fails when `springBootVersion` is set to 2.0.1.RELEASE and passes when the version is any previous release. The test failure is due to the following exception.
```
java.lang.NoSuchMethodError: org.yaml.snakeyaml.nodes.ScalarNode.getStyle()Ljava/lang/Character;

	at org.springframework.boot.env.OriginTrackedYamlLoader$KeyScalarNode.<init>(OriginTrackedYamlLoader.java:124)
...
```

**Comment by pivotal-dylan-roberts** [comment]
Thanks @wilkinsona! Will do.

**Comment by adrian-baker** [comment]
Was this ever raised as a Gradle issue?

**Comment by wilkinsona** [comment]
https://github.com/gradle/gradle/issues/4979
