### ISSUE TITLE
java -jar fails to read aspectjrt 1.7.4

### ISSUE THREAD

**Issue by PerGon** [spring-projects/spring-boot#203]
Hi there,

I have this gradle.build config file:

``` java
buildscript {
    repositories {
        maven { url "http://repo.spring.io/libs-snapshot" }
        mavenLocal()
    }
    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:0.5.0.M7")
    }
}

apply plugin: 'spring-boot'
apply plugin: 'java'
apply plugin: 'idea'

sourceCompatibility = 1.7
version = '0.1-alpha'

compileJava.options.encoding = 'UTF-8'

repositories {
    mavenCentral()
    maven { url "http://repo.spring.io/libs-snapshot" }
}

jar {
    manifest {
        attributes 'Implementation-Title': 'SysMonCore', 'Implementation-Version': version
        manifest.attributes("Main-Class": "com.sysmon.Application")
    }

    println "gradle version -> " + gradle.gradleVersion

    doLast{
        copy {
            from 'application.properties'
            from 'keystore.pfx'
            into 'build/libs'
        }
    }
}

dependencies {
    compile 'org.springframework.boot:spring-boot-starter-web:0.5.0.M7',
            'org.springframework.boot:spring-boot-starter-aop:0.5.0.M7',
            'org.springframework.boot:spring-boot-starter-data-jpa:0.5.0.M7',
            'org.springframework.boot:spring-boot-starter-jdbc:0.5.0.M7',
            'org.springframework.boot:spring-boot-starter-security:0.5.0.M7',
            'com.google.guava:guava:15.0',
            'mysql:mysql-connector-java:5.1.27',
            'org.projectlombok:lombok:1.12.2',
            'org.codehaus.groovy:groovy:2.1.9',
            'com.fasterxml.jackson.core:jackson-databind:2.3.0'
}

task wrapper(type: Wrapper) { gradleVersion = '1.10' }
```

Nothing fancy, I guess.
When I build using the spring-boot version 0.5.0.M6, everything works well. I do "java -jar myapp.jar" and my app starts nice and neat.

But after updating to spring-boot version 0.5.0.M7 (as seen in my gradle.config), I do "java -jar myapp.jar" and I get this stacktrace error:

``` java

java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
    at java.lang.Thread.run(Thread.java:724)
Caused by: java.lang.NoClassDefFoundError: org/aspectj/lang/ProceedingJoinPoint
    at java.lang.Class.getDeclaredMethods0(Native Method)
    at java.lang.Class.privateGetDeclaredMethods(Class.java:2521)
    at java.lang.Class.getDeclaredMethods(Class.java:1845)
    at org.springframework.orm.jpa.support.PersistenceAnnotationBeanPostProcessor.findPersistenceMetadata(PersistenceAnnotationBeanPostProcessor.java:402)
    at org.springframework.orm.jpa.support.PersistenceAnnotationBeanPostProcessor.postProcessMergedBeanDefinition(PersistenceAnnotationBeanPostProcessor.java:332)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyMergedBeanDefinitionPostProcessors(AbstractAutowireCapableBeanFactory.java:908)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:512)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:475)
    at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:304)
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:300)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:195)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:700)
    at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:760)
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:482)
    at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:124)
    at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:609)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:321)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:806)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:795)
    at com.sysmon.Application.main(Application.java:20)
    ... 6 more
Caused by: java.lang.ClassNotFoundException: org.aspectj.lang.ProceedingJoinPoint
    at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at org.springframework.boot.loader.LaunchedURLClassLoader.findClass(LaunchedURLClassLoader.java:148)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at org.springframework.boot.loader.LaunchedURLClassLoader.doLoadClass(LaunchedURLClassLoader.java:131)
    at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:103)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 27 more
Caused by: java.util.zip.ZipException: invalid stored block lengths
    at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:164)
    at org.springframework.boot.loader.jar.ZipInflaterInputStream.read(ZipInflaterInputStream.java:52)
    at sun.misc.Resource.getBytes(Resource.java:124)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:444)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    ... 35 more
2014-01-09 13:43:29.826  INFO 6930 --- [       Thread-2] ationConfigEmbeddedWebApplicationContext : Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@4018f058: startup date [Thu Jan 09 13:43:21 CET 2014]; root of context hierarchy
2014-01-09 13:43:29.857  WARN 6930 --- [       Thread-2] ationConfigEmbeddedWebApplicationContext : Exception thrown from LifecycleProcessor on context close

java.lang.IllegalStateException: LifecycleProcessor not initialized - call 'refresh' before invoking lifecycle methods via the context: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@4018f058: startup date [Thu Jan 09 13:43:21 CET 2014]; root of context hierarchy
    at org.springframework.context.support.AbstractApplicationContext.getLifecycleProcessor(AbstractApplicationContext.java:359)
    at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:888)
    at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.doClose(EmbeddedWebApplicationContext.java:153)
    at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:809)

2014-01-09 13:43:29.858  INFO 6930 --- [       Thread-2] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2014-01-09 13:43:29.867  INFO 6930 --- [ost-startStop-1] com.sysmon.ApplicationBootstrap          : ServletContext destroyed
```

It doesn't find the class "org.aspectj.lang.ProceedingJoinPoint", and the corresponding jar is in place. I guess the problem is somewhere here: java.util.zip.ZipException: invalid stored block lengths. But I have no clues where to start!
