### ISSUE TITLE
Does not work with Spring Data Ingalls-RC1: NoSuchMethodError: RepositoryRestConfiguration.setBasePath

### ISSUE THREAD

**Issue by candrews** [spring-projects/spring-boot#7806]
When using Spring Boot with Spring Data releasetrain Ingalls RC1 (following the directions from the documentation to set the property `spring-data-releasetrain.version` to `Ingalls-RC1`), this error occurs at startup:
```
Caused by: java.lang.NoSuchMethodError: org.springframework.data.rest.core.config.RepositoryRestConfiguration.setBasePath(Ljava/lang/String;)V
	at org.springframework.boot.autoconfigure.data.rest.RepositoryRestProperties.applyTo(RepositoryRestProperties.java:167) ~[spring-boot-autoconfigure-1.4.3.RELEASE.jar:1.4.3.RELEASE]
	at org.springframework.boot.autoconfigure.data.rest.SpringBootRepositoryRestConfigurer.configureRepositoryRestConfiguration(SpringBootRepositoryRestConfigurer.java:45) ~[spring-boot-autoconfigure-1.4.3.RELEASE.jar:1.4.3.RELEASE]
```

The documentation at https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.4-Release-Notes indicates that this should work.

The problem is caused by https://github.com/spring-projects/spring-data-rest/commit/5269a7d175935d03c86f0f39a48df7d3fb58457f

**Comment by snicoll** [comment]
ping @olivergierke

**Comment by snicoll** [comment]
Unfortunately, Spring Data broke binary compatibility with a class we're using so we can no longer offer a support for it in 1.4.x (I've removed the release notes section you referenced). Spring Boot `1.5.0.RC1` is going to be released this week so you should be able to use that with `Ingalls-RC1`.
