### ISSUE TITLE
Spring boot 2.0.0 - 2.0.6.RELEASE could not use log4j2 

### ISSUE THREAD

**Issue by lanpioneer** [spring-projects/spring-boot#15149]
Since I upgrade Spring boot from 1.5.9.RELEASE to 2.0 (includes 2.0.0-2.0.6.RELEASE), It was nightmare in Log4j2. 
I googled all information about lunched exception, but could not get any resolving plan. 
Here is my pom.xml

    <groupId>test</groupId>
    <artifactId>log4j2-test</artifactId>
    <version>1.0</version>
    <packaging>jar</packaging>

    <name>log4j-test</name>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <deploy.file.type>tar.gz</deploy.file.type>
        <spring-boot.version>2.0.6.RELEASE</spring-boot.version>
        <java.version>11</java.version>
    </properties>
    <parent>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-parent</artifactId>
	<version>2.1.0.RELEASE</version>
    </parent>

 <dependencies>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
            <exclusions>
		<exclusion>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-logging</artifactId>
		</exclusion>
	</exclusions>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-log4j2</artifactId>
        </dependency>

   </dependencies> 

Above setting in Spring boot 1.5.9.RELEASE is effect, but in 2.0.x, When I lunched, following exception was expected:
Failed to instantiate SLF4J LoggerFactory
Reported exception:
java.lang.NoClassDefFoundError: org/apache/logging/log4j/spi/AbstractLoggerAdapter
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)

Once I added dependency of slf4j
<dependency>
		    <groupId>org.slf4j</groupId>
		    <artifactId>slf4j-simple</artifactId>
		    <version>1.6.6</version>
		</dependency>
The exception was disappeared. But! The log4j2.xml was not effect for logging setting, Even though, I specify 
logging:
    config: classpath:log4j2.xml
in application.yml, I got the difference exception:
Logging system failed to initialize using configuration from 'classpath:log4j2.xml'
java.lang.IllegalStateException: Could not initialize Java logging from classpath:log4j2.xml
	at org.springframework.boot.logging.java.JavaLoggingSystem.loadConfiguration(JavaLoggingSystem.java:108)
	at org.springframework.boot.logging.java.JavaLoggingSystem.loadConfiguration(JavaLoggingSystem.java:92)
	at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithSpecificConfig(AbstractLoggingSystem.java:67)
	at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:57)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:269)

In an accidental situation， at your issue list, I found someone succeeded using Lo4j2 in Spring boot 2.1.0.RELEASE, and I found that's true, (Maybe you could suggest me upgrade Spring boot 2.1.0.RELEASE) But the important thing is, I finally purpose is integrated Spring Integration in Spring boot, and I found Spring boot 2.1.0.RELEASE could not support Spring Integration. 
Here is the error compilation error message On Spring boot 2.1.0.RELEASE 

Description	Resource	Path	Location	Type
Failed to read artifact descriptor for org.springframework:spring-jms:jar:5.1.2.RELEASE

org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for org.springframework:spring-jms:jar:5.1.2.RELEASE
Failed to read artifact descriptor for org.springframework.boot:spring-boot-starter-activemq:jar:2.1.0.RELEASE

org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for org.springframework.boot:spring-boot-starter-activemq:jar:2.1.0.RELEASE
Failed to read artifact descriptor for org.springframework.boot:spring-boot-starter-integration:jar:2.1.0.RELEASE

org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for org.springframework.boot:spring-boot-starter-integration:jar:2.1.0.RELEASE
Failed to read artifact descriptor for org.springframework.integration:spring-integration-activiti:jar:2.0.3.RELEASE

org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for org.springframework.integration:spring-integration-activiti:jar:2.0.3.RELEASE
Failed to read artifact descriptor for org.springframework.integration:spring-integration-core:jar:5.1.0.RELEASE

org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for org.springframework.integration:spring-integration-core:jar:5.1.0.RELEASE
Failed to read artifact descriptor for org.springframework.integration:spring-integration-jms:jar:5.1.0.RELEASE

org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for org.springframework.integration:spring-integration-jms:jar:5.1.0.RELEASE

The integrated of Spring Integration pom.xml content:

	<groupId>com.test</groupId>
	<artifactId>spring.integration.jsmgateway.server</artifactId>
	<version>0.0.1</version>
	<packaging>jar</packaging>

	<name>spring.integration.jsmgateway.server</name>
	<description>Spring Integration</description>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.1.0.RELEASE</version>
		<relativePath/> 
	</parent>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>1.8</java.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
			<exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-logging</artifactId>
                </exclusion>
            </exclusions>
		</dependency>
		
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-integration</artifactId>
		</dependency>
		
		<dependency>
		    <groupId>org.springframework.integration</groupId>
		    <artifactId>spring-integration-core</artifactId>
		    
		</dependency>
		<dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-jms</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.integration</groupId>
            <artifactId>spring-integration-jms</artifactId>
        </dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-activemq</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>

		
		

	</dependencies>

So could you please help me or give me some advice Thanks!

**Comment by wilkinsona** [comment]
That’s good to hear. Thanks for letting us know.
