### ISSUE TITLE
/configprops broken with Jackson 2.6.5

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-boot#5064]
We are starting to see Jackson 2.6.5 in the wild (Spring Cloud pulls it in somewhere) and it breaks the /configprops endpoint:

```
2016-02-01 15:45:45.680 ERROR [testsleuthzipkin,,,] 4172 --- [nio-3380-exec-7] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler processing failed; nested exception is java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.ser.impl.SimpleFilterProvider.addFilter(Ljava/lang/String;Lcom/fasterxml/jackson/databind/ser/impl/SimpleBeanPropertyFilter;)Lcom/fasterxml/jackson/databind/ser/impl/SimpleFilterProvider;] with root cause

java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.ser.impl.SimpleFilterProvider.addFilter(Ljava/lang/String;Lcom/fasterxml/jackson/databind/ser/impl/SimpleBeanPropertyFilter;)Lcom/fasterxml/jackson/databind/ser/impl/SimpleFilterProvider;
	at org.springframework.boot.actuate.endpoint.ConfigurationPropertiesReportEndpoint.applyCglibFilters(ConfigurationPropertiesReportEndpoint.java:196) ~[spring-boot-actuator-1.3.2.RELEASE.jar:1.3.2.RELEASE]
	at org.springframework.boot.actuate.endpoint.ConfigurationPropertiesReportEndpoint.configureObjectMapper(ConfigurationPropertiesReportEndpoint.java:175) ~[spring-boot-actuator-1.3.2.RELEASE.jar:1.3.2.RELEASE]
```

**Comment by wilkinsona** [comment]
Spring Boot 1.3.2 uses 2.6.5 so I'm surprised that this is broken. Perhaps we're missing a test.

**Comment by dsyer** [comment]
Hmm. I thought it was going to be simple.

**Comment by wilkinsona** [comment]
Doesn't seem to be simple. It'd fail to compile if the method had really disappeared. Also, I just tried the Actuator sample and `configprops` worked fine with 2.6.5.

**Comment by dsyer** [comment]
It's simple (or rather I am). I am getting Jackson 2.1 in one of the Spring Cloud samples - we need to fix it there.
