### ISSUE TITLE
bug or error in spring 5.2 with springboot 2.2.0.m3?

### ISSUE THREAD

**Issue by nikkisingh111333** [spring-projects/spring-boot#18217]
After doing 2 hours of upgrading project from spring 5.1 to 5.2 and from 2.1 to 2.2 i m getting following errors always:

first is: ON deploying.

```
java.lang.NoSuchFieldError: EXHAUSTIVE
	at org.springframework.boot.BeanDefinitionLoader.isComponent(BeanDefinitionLoader.java:286) ~[spring-boot-2.2.0.M3.jar:2.2.0.M3]
	at org.springframework.boot.BeanDefinitionLoader.load(BeanDefinitionLoader.java:158) ~[spring-boot-2.2.0.M3.jar:2.2.0.M3]
	at org.springframework.boot.BeanDefinitionLoader.load(BeanDefinitionLoader.java:136) ~[spring-boot-2.2.0.M3.jar:2.2.0.M3]
	at org.springframework.boot.BeanDefinitionLoader.load(BeanDefinitionLoader.java:128) ~[spring-boot-2.2.0.M3.jar:2.2.0.M3]
	at org.springframework.boot.SpringApplication.load(SpringApplication.java:724) ~[spring-boot-2.2.0.M3.jar:2.2.0.M3]
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:399) ~[spring-boot-2.2.0.M3.jar:2.2.0.M3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:317) ~[spring-boot-2.2.0.M3.jar:2.2.0.M3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1275) ~[spring-boot-2.2.0.M3.jar:2.2.0.M3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1263) ~[spring-boot-2.2.0.M3.jar:2.2.0.M3]
	at GamOney2.GamOney2.GamOney2Application.main(GamOney2Application.java:18) ~[classes/:na]`
second one is when calling databaseClient with postgres:
`		PostgresqlConnectionFactory h2c=new PostgresqlConnectionFactory(PostgresqlConnectionConfiguration.builder()
	    		.schema("public")
	    		.host("localhost")
	    		.username("postgres")
	    		.password("nikkibro0")  //Recative method chaining for PostgresSQL DB connection and configuration
	    		.port(5432)
	    		.database("postgres")
    		.build());
		System.out.println(DatabaseClient.create(h2c).execute().sql("select * from testdb2").as(testdb2.class).fetch().all().cache().collectList().block().get(0).name);
```

AFTER CALLING THIS CODE I'M GETTING

```
Exception in thread "main" java.lang.NoSuchMethodError: org.springframework.transaction.reactive.TransactionSynchronizationManager.currentTransaction()Lreactor/core/publisher/Mono;
	at org.springframework.data.r2dbc.connectionfactory.ConnectionFactoryUtils.doGetConnection(ConnectionFactoryUtils.java:88)
	at org.springframework.data.r2dbc.connectionfactory.ConnectionFactoryUtils.getConnection(ConnectionFactoryUtils.java:70)
	at org.springframework.data.r2dbc.core.DefaultDatabaseClient.getConnection(DefaultDatabaseClient.java:189)
	at org.springframework.data.r2dbc.core.DefaultDatabaseClient.inConnectionMany(DefaultDatabaseClient.java:170)
	at org.springframework.data.r2dbc.core.DefaultFetchSpec.all(DefaultFetchSpec.java:75)
	at org.springframework.data.r2dbc.core.DefaultSqlResult.all(DefaultSqlResult.java:140)
	at GamOney2.GamOney2.test_r2dbc.main(test_r2dbc.java:37)
```

here's my pom.xml AND i'm pretty sure that my pom.xml is somehow wrong. I'm getting this after upgrading to 5.2 reactor & 2.2 spring boot.I REALLY want to use reactive programming.
check  my pom.xml:
[pom.TXT](https://github.com/spring-projects/spring-boot/files/3607501/pom.TXT)
