### ISSUE TITLE
Tolerate breaking API changes in jackson-joda 2.5.1

### ISSUE THREAD

**Issue by lbeuster** [spring-projects/spring-boot#2573]
JacksonAutoConfig now pulls in jackson-joda support and uses  com.fasterxml.jackson.datatype.joda.ser.JacksonJodaFormat which is not available in jackson 2.5.1 anymore

switching back to spring-boot 1.2.1 or jackson 2.4.x solves the problem.

-> Could not evaluate condition on org.springframework.boot.autoconfigure.jackson.JacksonAutoConfiguration$JacksonObjectMapperConfiguration#jacksonObjectMapper due to internal class not found....
Caused by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/datatype/joda/ser/JacksonJodaFormat

**Comment by wilkinsona** [comment]
Boot 1.2 has never intentionally worked with Jackson 2.5. It may have done so by happy accident, but Jackson 2.4 is the supported version. Boot 1.3 will move to Jackson 2.5 (#2332)

**Comment by ceefour** [comment]
:+1: for this

**Comment by erikyuzwa** [comment]
for anyone else pulling their hair out over ancient Spring code now in 2018, `com.fasterxml.jackson.datatype.joda.ser.JacksonJodaFormat` was updated to `com.fasterxml.jackson.datatype.joda.cfg.JacksonJodaDateFormat` if you're using jackson 2.5+
