### ISSUE TITLE
Annotated Bean Function Matching on actual Returned Instance instead of Function Return Type

### ISSUE THREAD

**Issue by MrThreepwood** [spring-projects/spring-boot#47856]
When upgrading from Spring 3.5.4 to 3.5.5, I'm receiving the error `expected single matching bean but found 2` when attempting to provide a unique bean definition for IStreamConsumerFactory.

These beans signature specify that they provide a IStreamConsumerFactory, and an IHistoricalStreamConsumerFactory.

The IHistoricalStreamConsumerFactory does NOT implement IStreamConsumerFactory, but the actual implementations of the IHistroicalStreamConsumerFactory do. Prior to 3.5.5 this wasn't an issue.

I have not created a simple example, but I assume that

```
interface A

interface B

class AImpl: A

class BImpl: A, B

@Bean
fun aFactory(): A {
  return AImple()
}

@Bean
fun bFactory(): B {
  return BImple()
}
```
Would be a bare minimum recreation of the issue that would cause a failure as soon as something requested an `A`
