### ISSUE TITLE
NoClassDefFoundError: MappingMessageRouterManagement

### ISSUE THREAD

**Issue by taraktikos** [spring-projects/spring-boot#3911]
After upgrading spring boot from 1.3.0.M4 to 1.3.0.M5 i get error

``` 
Caused by: java.lang.NoClassDefFoundError: org/springframework/integration/router/MappingMessageRouterManagement
	at org.springframework.integration.dsl.RouterSpec.subFlowMapping(RouterSpec.java:123)
	at demo.CafedemoApplication$1.accept(CafedemoApplication.java:109)
	at demo.CafedemoApplication$1.accept(CafedemoApplication.java:105)
	at org.springframework.integration.dsl.IntegrationFlowDefinition.route(IntegrationFlowDefinition.java:1561)
	at org.springframework.integration.dsl.IntegrationFlowDefinition.route(IntegrationFlowDefinition.java:1543)
	at org.springframework.integration.dsl.IntegrationFlowDefinition.route(IntegrationFlowDefinition.java:1485)
	at org.springframework.integration.dsl.IntegrationFlowDefinition.route(IntegrationFlowDefinition.java:1440)
	at demo.CafedemoApplication.orders(CafedemoApplication.java:84)
	at demo.CafedemoApplication$$EnhancerBySpringCGLIB$$88578031.CGLIB$orders$1(<generated>)
	at demo.CafedemoApplication$$EnhancerBySpringCGLIB$$88578031$$FastClassBySpringCGLIB$$eaa7094c.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:318)
	at demo.CafedemoApplication$$EnhancerBySpringCGLIB$$88578031.orders(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
```

**Comment by wilkinsona** [comment]
The version of the Spring Integration Java DSL that you're using is incompatible with Spring Integration 4.2.0.RC1. AFAIK, there's no release of the Java DSL that's compatible with Spring Integration 4.2.0 so you'll need to use a snapshot for the time being.

/cc artembilan

**Comment by artembilan** [comment]
Hi @taraktikos !

Thank you for feedback.
Yes, we definitely need a SI Java DSL version compatible with SI-4.2 and therefore with Boot-1.3 and IO-2.0 afterwards.

You need just to wait for this Wednesday when we release 1.1.0.M2. Meanwhile you should use BUILD-SNAPSHOT.

That's all!
