### PR TITLE
Fix upstream RSocket method renames

### PR DESCRIPTION
**Pull request by dreis2211**
Hi,

this PR fixes two compilation errors introduced by https://github.com/spring-projects/spring-framework/commit/45d0405624a8e91a686c670119e0f9618b2d063e .

Cheers,
Christoph

### CODE REVIEW

**Comment by wilkinsona** [comment]
Thanks very much once again, @dreis2211.
