### ISSUE TITLE
UndertowWebServerFactoryCustomizer requires commons lang via an unintended import on ClassUtils

### ISSUE THREAD

**Issue by ionelmanolache** [spring-projects/spring-boot#23059]
Hi,

I use Undertow and after upgraded to v2.3.3, app failed to start with error NoClassDefFoundError;org.apache.commons.lang.ClassUtils in 'UndertowWebServerFactoryCustomizer'
(see commit log https://github.com/spring-projects/spring-boot/commit/f0d90020e55a06cd9840040e2ec6709591a6e93a)

file https://github.com/spring-projects/spring-boot/commits/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/embedded/UndertowWebServerFactoryCustomizer.java

Thank you and best regards,
Ionel.

**Comment by snicoll** [comment]
Oops, thank you very much for the report. We meant to import `ClassUtils` from the core framework there.

**Comment by wilkinsona** [comment]
This needs to be fixed in 2.2.x too. Thankfully we haven't released that one yet.

**Comment by snicoll** [comment]
The import should have been prevented by a Checkstyle rule. Unfortunately it doesn't work as expected, I've created a separate issue to revisit it (#23062)
