### ISSUE TITLE
Dependencies in testAndDevelopmentOnly leak into bootJar when a different version of the same dependency is on the runtime classpath

### ISSUE THREAD

**Issue by jimisola** [spring-projects/spring-boot#50762]
## Spring Boot version

4.1.0

## Problem

When a dependency declared as `testAndDevelopmentOnly` transitively pulls `org.springframework.boot:spring-boot-testcontainers` with `compile` scope in its POM, the artifact ends up inside the fat jar produced by `bootJar`. The Spring Boot BOM (4.1.0) constrains `org.testcontainers:testcontainers` to test scope, so the actual Testcontainers library is *not* included. The result is a `NoClassDefFoundError: org/testcontainers/lifecycle/Startable` at startup — thrown from `TestcontainersLifecycleBeanPostProcessor` which is present in the jar but missing its dependency.

This regression is triggered by the **combination** of Spring Boot Gradle plugin 4.1.0 and Spring Boot BOM 4.1.0. Neither alone reproduces it:

| Spring Boot Gradle plugin | Spring Boot BOM | Leak? |
|---|---|---|
| 4.0.6 | 4.0.6 | No |
| 4.1.0 | 4.0.6 | No |
| 4.0.6 | 4.1.0 | No |
| **4.1.0** | **4.1.0** | **Yes** |

## Reproduction

Add a library that declares `spring-boot-testcontainers` as `compile`-scoped (e.g. `io.arconia:arconia-dev-services-core:0.27.1`) via `testAndDevelopmentOnly`:

```kotlin
// build.gradle.kts
plugins {
    id("org.springframework.boot") version "4.1.0"
}

dependencies {
    testAndDevelopmentOnly("io.arconia:arconia-dev-services-rabbitmq:0.27.1")
}
```

Run `./gradlew bootJar` and inspect:

```
jar tf build/libs/app.jar | grep testcontainers
# BOOT-INF/lib/spring-boot-testcontainers-4.1.0.jar  ← present
# org.testcontainers:testcontainers                   ← absent
```

Start the app:

```
Caused by: java.lang.NoClassDefFoundError: org/testcontainers/lifecycle/Startable
    at org.springframework.boot.testcontainers.lifecycle.TestcontainersLifecycleBeanPostProcessor.postProcessAfterInitialization(TestcontainersLifecycleBeanPostProcessor.java:86)
```

## Expected behavior

`testAndDevelopmentOnly` exclusion prevents `spring-boot-testcontainers` from entering `bootJar`, as it did with plugin 4.0.6.

## Workaround

```kotlin
configurations.named("runtimeClasspath") {
    exclude(group = "org.springframework.boot", module = "spring-boot-testcontainers")
    exclude(group = "org.testcontainers")
}
```

**Comment by idsoke** [comment]
Thanks for the very thorough reproduction matrix — narrowing it down to specifically the 4.1.0 plugin + 4.1.0 BOM combination is a great lead.

I'd like to help investigate this if that's welcome. From the symptoms (spring-boot-testcontainers leaking into bootJar while the actual
org.testcontainers:testcontainers core jar is correctly excluded via the BOM's test-scope constraint), this looks like an inconsistency in how the Gradle plugin's
developmentOnly/testAndDevelopmentOnly exclusion logic interacts with dependency-management scope constraints, possibly changed between 4.0.6 and 4.1.0.
 
I'll try bisecting spring-boot-gradle-plugin between v4.0.6 and v4.1.0 and reproduce locally with the arconia-dev-services-rabbitmq example from the issue. Will
report back with findings, and a PR if I can pin down a clear fix.

**Comment by wilkinsona** [comment]
@jimisola when you were configuring the mismatched versions of `spring-boot-dependencies` and Spring Boot's Gradle plugin, how were you doing so?

**Comment by jimisola** [comment]
@wilkinsona To answer your question: the mismatched combinations in the matrix were configured by adding an explicit Gradle-native platform import in `dependencies {}`, independent of the plugin version:

```kotlin
dependencies {
    implementation(platform("org.springframework.boot:spring-boot-dependencies:4.0.6")) // or 4.1.0
    implementation("org.springframework.boot:spring-boot-starter")
    testAndDevelopmentOnly("io.arconia:arconia-dev-services-rabbitmq:0.27.1")
}
```

I reproduced this in a MWE and was able to narrow down the root cause:

**Repro 1** — plugin `4.1.0` + `implementation(platform("org.springframework.boot:spring-boot-dependencies:4.1.0"))` → leaks, and running the jar throws the reported `NoClassDefFoundError: org/testcontainers/lifecycle/Startable`.

**Repro 2** — same plugin `4.1.0`, but platform pinned to `4.0.6` → no leak. Matches the "No" row in the matrix.

Comparing `gradle dependencies` output for the two configurations involved in the `productionRuntimeClasspath = runtimeClasspath - (developmentOnly + testAndDevelopmentOnly)` subtraction (repro 1):

| Configuration | `spring-boot-testcontainers` resolves to |
|---|---|
| `testAndDevelopmentOnly` | `4.0.6` (arconia 0.27.1's natural transitive version — `testAndDevelopmentOnly` doesn't extend `implementation`, so it never sees the explicit `platform(...)` constraint) |
| `runtimeClasspath` | `4.1.0` (upgraded via the `implementation(platform(...))` constraint: `4.0.6 -> 4.1.0`) |

Because the two configurations resolve **different versions** of `org.springframework.boot:spring-boot-testcontainers`, the subtraction doesn't recognize them as the same dependency, so `spring-boot-testcontainers-4.1.0.jar` survives into `productionRuntimeClasspath` and gets packaged into `bootJar`.

By contrast, `org.testcontainers:testcontainers:2.0.5` resolves identically in both configurations (same version in both the 4.0.6 and 4.1.0 `spring-boot-testcontainers` POMs), so it *is* correctly matched and excluded — which is why only `spring-boot-testcontainers` leaks while the actual Testcontainers jar is absent.

So the trigger isn't really "plugin 4.1.0 + BOM 4.1.0" per se, but: an explicit dependency platform/BOM import that upgrades `spring-boot-testcontainers` on `runtimeClasspath` to a version different from the one a `testAndDevelopmentOnly` dependency naturally resolves to on its own. The version-based identity comparison used for the `developmentOnly`/`testAndDevelopmentOnly` exclusion then fails to match the two, and the upgraded artifact leaks into the executable jar.


---

Following up on the analysis above: I'd classify this as a `spring-boot-gradle-plugin` bug rather than an issue with `arconia-dev-services-rabbitmq` itself.

`arconia-dev-services-rabbitmq:0.27.1` declaring `spring-boot-testcontainers` as a normal `compile`-scoped (transitive) dependency at `4.0.6` is unremarkable — that's just a library built against Boot 4.0.x. The bug is that the plugin's `productionRuntimeClasspath = runtimeClasspath - (developmentOnly + testAndDevelopmentOnly)` exclusion implicitly assumes a given module resolves to the *same version* in `runtimeClasspath` and in `developmentOnly`/`testAndDevelopmentOnly`. That assumption doesn't hold once a BOM/platform constraint applies to `runtimeClasspath` (via `implementation`) but not to `testAndDevelopmentOnly` (which doesn't extend `implementation` and therefore isn't subject to the same constraints).

Two possible fix directions:
1. Make the `productionRuntimeClasspath` subtraction match excluded entries by module coordinates (`group:artifact`) rather than exact `group:artifact:version`, so a version bump from a BOM constraint doesn't defeat the exclusion.
2. Apply the same dependency constraints/platforms to `testAndDevelopmentOnly` as are applied to `implementation`/`runtimeClasspath`, so both configurations resolve the same version for shared modules and the existing exact-match subtraction continues to work.

Happy to help test a fix against either approach using the repro projects above if useful.

**Comment by wilkinsona** [comment]
> Following up on the analysis above: I'd classify this as a spring-boot-gradle-plugin bug rather than an issue with arconia-dev-services-rabbitmq itself.

I'm not yet sure that I agree with this. I think it could equally be classified as a misconfiguration in your build as the platform dependency hasn't been applied consistently.

This is a general-purpose fix/workaround that prevents such inconsistencies from occurring:

```
configurations {
	testAndDevelopmentOnly.shouldResolveConsistentlyWith(runtimeClasspath)
}
```

Boot plugin could do this in its Java plugin as part of creating the `testAndDevelopmentOnly` configuration but I haven't yet convinced myself it's the right thing to do and that it won't have unwanted side-effects. I can't think of a situation where you'd actually want different versions, but that's effectively what you're asking for by not applying the platform consistently. If someone's doing that intentionally, the above would break them in a way that they may struggle to work around.

**Comment by jimisola** [comment]
That workaround fixes it completely in my repro:

```kotlin
configurations {
	testAndDevelopmentOnly {
		shouldResolveConsistentlyWith(named("runtimeClasspath").get())
	}
}
```

`testAndDevelopmentOnly` now resolves `spring-boot-testcontainers` to `4.1.0` (matching `runtimeClasspath`), the exclusion matches correctly, `bootJar` no longer contains `spring-boot-testcontainers`, and the app starts cleanly.

Fair point on the framing, but two things from our side:

1. This combination worked fine with the 4.0.x plugin, so from our POV it's a regression — something that used to produce a working artifact now silently doesn't.
2. It's a *silent* failure: the build and `bootJar` both succeed, and the only sign of trouble is `NoClassDefFoundError` at runtime.

Given that, would it be worth baking `shouldResolveConsistentlyWith(runtimeClasspath)` into the Boot plugin's `testAndDevelopmentOnly`/`developmentOnly` configurations by default? That would turn this into a loud build-time failure instead of a silent runtime one, regardless of how the regression itself gets classified.

**Comment by wilkinsona** [comment]
>  regardless of how the regression itself gets classified

Just to be clear, this isn't a regression. The same problem occurs with Spring Boot 4.0.x, for example:

```
plugins {
	id 'java'
	id 'org.springframework.boot' version '4.0.7'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

repositories {
	mavenCentral()
}

dependencies {
	implementation(platform("org.springframework.boot:spring-boot-dependencies:4.0.7"))
	implementation("org.springframework.boot:spring-boot-starter")
	testAndDevelopmentOnly("io.arconia:arconia-dev-services-rabbitmq:0.27.1")
}
```

Here, the two versions of `spring-boot-testcontainers` are 4.0.6 and 4.0.7.

**Comment by ThomasVitale** [comment]
Isn't this the problematic part which is not fully supported by the Spring Boot plugin?

```groovy
dependencies {
	implementation(platform("org.springframework.boot:spring-boot-dependencies:4.0.7"))
}
```

Gradle will only apply the platform dependencies to the "standard" configurations (e.g. `implementation`, `testImplementation`). Since the `testAndDevelopmentOnly` configuration comes from the Spring Boot plugin and not from the Java plugin, Gradle will not apply the platform there, hence versioning issues (and consequent issues in the Spring Boot plugin processing of test/development dependencies).

When using a setup based on the Spring Boot plugins `org.springframework.boot` and `io.spring.dependency-management` (no platform dependency), I don't experience any error: https://github.com/ThomasVitale/reproducer-spring-boot-4-1-dev-services

If it's the intended behaviour, perhaps the docs should be updated to describe the limitations of using a platform dependency instead of the Spring Boot dependency management plugin: https://docs.spring.io/spring-boot/gradle-plugin/managing-dependencies.html#managing-dependencies.gradle-bom-support

**Comment by wilkinsona** [comment]
Yes, that's the problematic part. It's what I was referring to above when I said that the platform's applied inconsistently.

If you have consistent dependency management/constraints across configurations then the problem does not occur. As your sample demonstrates, @ThomasVitale, using `io.spring.dependency-management` is another way to do this as it applies its dependency management to all configurations. However, it only helps if the dependency with different versions in different configurations is managed by `spring-boot-dependencies`.

What we need to decide is how far we can go on the Boot side when the dependency management/constraints are inconsistent.  There are risks as it's impossible for us to distinguish between different versions that are accidental and that are intentional. We have [applied fixes in this area in the past](https://github.com/spring-projects/spring-boot/issues/46043) and that issue demonstrates that a similar problem was possible even when using the Dependency Management Plugin.

**Comment by wilkinsona** [comment]
> If it's the intended behaviour, perhaps the docs should be updated to describe the limitations of using a platform dependency instead of the Spring Boot dependency management plugin

The section to which you linked already does so:

> A platform or enforced platform will only constrain the versions of the configuration in which it has been declared or that extend from the configuration in which it has been declared. As a result, in may be necessary to declare the same dependency in more than one configuration.

**Comment by jimisola** [comment]
One data point for the "how far can we go" question, not a request. The reason this stung is that it fails silently.

The build and bootJar both succeed, and the only signal is a runtime NoClassDefFoundError from inside the executable jar, so an inconsistency that's invisible at build time only shows up in production.

I appreciate you can't tell accidental skew from intentional and the call is yours; just flagging that silent build-success then runtime-failure shape as the part that's hard to catch.

**Comment by ThomasVitale** [comment]
I published another [reproducer](https://github.com/ThomasVitale/reproducer-spring-boot-4-testcontainers), this time using Spring Cloud AWS and their `io.awspring.cloud:spring-cloud-aws-testcontainers` module, which also comes with a transitive dependency to `org.springframework.boot:spring-boot-testcontainers`.

This results in Spring Boot Testcontainers to be included in the final JAR:

```groovy
dependencies {
    implementation(platform("org.springframework.boot:spring-boot-dependencies:4.0.7"))

    developmentOnly(platform("org.springframework.boot:spring-boot-dependencies:4.0.7"))
    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    
    testAndDevelopmentOnly "io.awspring.cloud:spring-cloud-aws-testcontainers:4.0.2"
}
```

this does NOT result in Spring Boot Testcontainers to be included in the final JAR:

```groovy
dependencies {
    implementation(platform("org.springframework.boot:spring-boot-dependencies:4.0.7"))

    developmentOnly(platform("org.springframework.boot:spring-boot-dependencies:4.0.7"))
    developmentOnly 'org.springframework.boot:spring-boot-devtools'
	
    testAndDevelopmentOnly(platform("org.springframework.boot:spring-boot-dependencies:4.0.7"))
    testAndDevelopmentOnly "io.awspring.cloud:spring-cloud-aws-testcontainers:4.0.2"
}
```

> The section to which you linked already does so:
> 
> > A platform or enforced platform will only constrain the versions of the configuration in which it has been declared or that extend from the configuration in which it has been declared. As a result, in may be necessary to declare the same dependency in more than one configuration.

Perhaps that section can be enhanced with a concrete example based on a `developmentOnly` dependency (e.g. Spring Boot DevTools) and a `testAndDevelopmentOnly` dependency, which I guess it's where the problem would typically manifest.
