### ISSUE TITLE
Downgrade to Jedis 2.8.1

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot#6677]
See https://jira.spring.io/browse/INT-4090 and breaking change introduced in https://github.com/xetorthio/jedis/pull/1301

/cc @artembilan

**Comment by artembilan** [comment]
@wilkinsona , that might not be related but I would like to share that somewhere with the team.

The latest Spring Data Redis (1.8.0) is based on Jedis-2.9.0 which is with the same `emptyList` issue.
So, Spring Integration 5.0 is going to fail sporadically again, because I can't stay with 2.8.1 there...

Thank you for your attention!

/cc @olivergierke , @christophstrobl , @mp911de

**Comment by mp911de** [comment]
It's possible to downgrade Jedis to {{2.8.1}} while using Spring Data Redis {{1.7.x}} but Spring Data Redis {{1.8.0}} requires Jedis {{2.9.0}}. Jedis changed constructors in {{2.9.0}} and using an earlier version runs into {{NoSuchMethodError}} on Redis Standalone usage.

I submitted a PR to restore the previous behavior (https://github.com/xetorthio/jedis/pull/1368).

**Comment by olivergierke** [comment]
@mp911de — Is that the only issue we have for the step from 2.8 to 2.9? I know changes like these are a PITA but maybe we can work around this by invoking the constructor reflectively and thus lower the minimum required dependency version back to 2.8?

Do the Jedis guys release preview versions of their releases? If so, we should definitely build against them and report issues like these back to them. Changing constructors in public API is quite a no-go for a minor release.

**Comment by mp911de** [comment]
Jedis added a new constructor and we switched to that new constructors in Spring Data Redis `1.8.0`. 

The Jedis guys have no pre-releases and they don't provide `SNAPSHOT`s. I'm not keen on building Jedis snapshots in our own build and running tests against these.

**Comment by artembilan** [comment]
How about to treat that `emptyList` as a `null` too in the `TransactionResultConverter.convert()`?
At least in  Spring Data Redis 1.8.0 and until Jedis fix in the 2.9.1...

I see similar issue in the `SrpConnection`:
```
private List<Object> closeTransaction() {
	List<Object> results = Collections.emptyList();
	if (txTracker != null) {
		results = getPipelinedResults(txTracker, false);
		txTracker.close();
		txTracker = null;
	}
	return results;
}
```
Hope you really will remove it soon :smile: : 
```
* @deprecated since 1.7. Will be removed in subsequent version.
```

**Comment by mp911de** [comment]
That's what we did for Spring Data `1.8.0.M1` but it's not correct - it removes the information whether a transaction was rolled back 😱 I submitted a PR to fix that issue in Jedis. We deprecated Srp and JRedis. These two will be removed with Spring Data Redis `2.0`.

You could give the lettuce driver a spin as Jedis and lettuce will remain as active drivers in Spring Data Redis.

**Comment by artembilan** [comment]
Oh! I see what you mean in `JedisConnection.exec()`:
```
return convertPipelineAndTxResults && !CollectionUtils.isEmpty(results)
```
So, our upgrade to Spring Data Redis 1.8.0 will bring our test back to green :smile: .
But anyway I will be happy to receive approval from @wilkinsona after fix for this Boot issue about downgrade to Jedis 2.8.1.

IMO the question is closed and we can simply go ahead with fix here.

@wilkinsona do you need PR on the matter?

**Comment by olivergierke** [comment]
Boot 1.4 can't downgrade as otherwise Redis projects won't work anymore. Why are you even concerned about Boot? Isn't it rather a matter of making Spring Integration work with Jedis 2.9?

**Comment by artembilan** [comment]
We fail against Spring IO, which now is based on Spring Boot 1.4, and that, in turn, is based on Jedis 2.8.2.
Our tests are fine, because we are still with Jedis 2.7.3.
But when we (or @wilkinsona) test it against IO, we fail sporadically. 
That is a bit annoying and eats a lot of our time to investigate :angry: 

Not sure what you mean about all other Redis projects, but currently Boot has this:
```
<jedis.version>2.8.2</jedis.version>
...
<spring-data-releasetrain.version>Hopper-BUILD-SNAPSHOT</spring-data-releasetrain.version>
```
Not sure who is Hopper (https://en.wikipedia.org/wiki/Grace_Hopper ?), but I guess it is about Spring Data Redis 1.7.x: https://github.com/spring-projects/spring-data-redis/blob/1.7.x/pom.xml#L26

**Comment by olivergierke** [comment]
Oh, your original comment mentioned SD Redis 1.8, which is Ingalls which made me think we're talking Boot 1.5. That should definitely upgrade to 2.9.

Generally speaking you're preaching to the choir when it comes to Jedis. It's been a nightmare ever since, especially in terms of incompatible changes in minor or even bugfix releases.

However, I think we should rather raise our concerns in their tracker (trust me, we have, not only once). As we're basically at their mercy and sometimes are forced to upgrade to be able to ship features requested by users on our side (cluster support being the latest example). There's no way for us to even foresee such changes as their neither publish preview releases nor snapshots.

That said, I'd be very much in favor of switching to Lettuce (the driver Mark maintains) as the default driver, but that switch is one that mostly has to be done by upstream projects as SD Redis already supports it. So it's not really a decision of the data team but the SI one, the Boot one and a platform decision.

**Comment by artembilan** [comment]
Eh, indeed we can switch to Lettuce in SI, because it is just a testing issue.
But at the same time Boot 1.4 must switch as well. For consistency.

Since it is test dependency there, too, that really looks more organic just downgrade and forget.
Everything rest is up to end-user to choose proper Redis driver in its application.

OTOH with the Lettuce we haven't caught that Jedis problem :smile: 

Right, there is nothing more to do from SD team side.

Thank you for your time and support!
