### PR TITLE
upgrade elasticsearch to 2.2.0

### LINKED ISSUE #5443: Upgrade to Elasticsearch 2.2
Hopper is using 2.2 and we're still on 1.7. Upgrade to 2.2 breaks the tests (mostly embedding)

### PR DESCRIPTION
**Pull request by htynkn**
Three major changes:
* package name change for `ClusterHealthStatus`
* `ImmutableSettings` was removed
* necessary param `path.home`

Fix #5443

### CODE REVIEW

**Comment by philwebb** [comment]
@htynkn I know I've asked before, but can you confirm that you've signed the CLA.

**Comment by htynkn** [comment]
@philwebb Yes, my confirmation number is 128120150629030655.

**Comment by snicoll** [comment]
I wonder if we couldn't provide a default temp directory location for this new property rather than requiring the user to provide it. I am not sure what was happening before 2.2 (no persistence maybe?)

**Comment by rajadileepkolli** [comment]
@snicoll it started from elasticsearch 2.0 as mandatory field so we are asking user to specify there they want elasticsearch to start in local environment

**Comment by snicoll** [comment]
@rajadileepkolli thanks for the answer. My question was what the behaviour before 1.7. Maybe we could make that more transparent for our users. Would you create a temporary directory by default? Or disable persistence?

**Comment by philnate** [comment]
@htynkn is your PR as well taking care of the ElasticsearchHealthSensor issue, which is caused by the ClusterHealthStatus package move? Can't spot anything like this in your PR, but I simply might miss it. If you have the elasticsearch healthsensor active and you try to visit /health you'll get this:

```
{
timestamp: 1459264185328,
status: 500,
error: "Internal Server Error",
exception: "java.lang.NoClassDefFoundError",
message: "org/elasticsearch/action/admin/cluster/health/ClusterHealthStatus",
path: "/mgmt/health"
}
```
Looks like the compiler is creating a compile time dependency on ES <2.2
Originating here: org/springframework/boot/actuate/health/ElasticsearchHealthIndicator.java:54

**Comment by htynkn** [comment]
@philnate thanks for your time to review pull request. Yes, you are right, sorry I didn't notice that issue. Looks like this pull request needs more work to check and fix, I would like to close this pull request first. If I get some time to fix issue and add default value for path.home, I can reopen this or create a new pull request. On 2016-03-30 05:07 , Philipp Knobel Wrote: @htynkn is your PR as well taking care of the ElasticsearchHealthSensor issue, which is caused by the ClusterHealthStatus package move? Can't spot anything like this in your PR, but I simply might miss it. If you have the elasticsearch healthsensor active and you try to visit /health you'll get this: {
timestamp: 1459264185328,
status: 500,
error: "Internal Server Error",
exception: "java.lang.NoClassDefFoundError",
message: "org/elasticsearch/action/admin/cluster/health/ClusterHealthStatus",
path: "/mgmt/health"
}
 Looks like the compiler is creating a compile time dependency on ES <2.2 Originating here: org/springframework/boot/actuate/health/ElasticsearchHealthIndicator.java:54 — You are receiving this because you were mentioned. Reply to this email directly or view it on GitHub

**Comment by philwebb** [comment]
Can we leave it open? It might still be a good starting point.

**Comment by snicoll** [comment]
@htynkn I was about to review this PR this week still. One thing would be to remove the `data` and `logs` properties since I guess the new `home` one should be enough. If you intend to rework this PR, please push force on your exist branch to update this PR (let's keep the history in a single place). Let me know if you have time to work on this in the coming days. Thanks!

**Comment by htynkn** [comment]
@snicoll Thanks. I have updated PR. with a properties "path.home", `logs` and `data` are not mandatory, so I remove them. 
About the issue philnate metioned, I only find `ClusterHealthStatus` in test and the package name change is already included in this PR. I'm not sure after upgrade elasticsearch to 2.2.0, it will works well or not.

**Comment by snicoll** [comment]
OK, I can take it from there I think. Thanks!

**Comment by snicoll** [comment]
ElasticSearch was using the current working directory as the default for the embedded node so I've kept that which means that all the other properties are now inferred from that. I've updated the doc and I think there are room for improvements for our elasticsearch support.
