### ISSUE TITLE
Kubernetes client version Updated faced errors in that .

### ISSUE THREAD

**Issue by Ramya-developer** [spring-projects/spring-boot#34535]
We are using spring boot version is 2.7.5 and kubernetes client version is 5.11.2 . Now when we upgrade kubernetes client version to 6.4.0 .we are facing below log .can you please suggest on this . is this any relation between springboot version ,kubernetes client version why it is getting like this.

{"timestamp":"2023-03-09T10:55:19.937Z","version":"0.3.0","message":"Application run failed","logger":"org.springframework.boot.SpringApplication","thread":"main",
"stack_trace":"java.lang.NoClassDefFoundError: io/fabric8/kubernetes/model/jackson/UnmatchedFieldTypeModule\n\tat io.fabric8.kubernetes.client.utils.
Serialization.<clinit>(Serialization.java:54)\n\tat io.fabric8.kubernetes.client.dsl.internal.OperationSupport.<clinit>(OperationSupport.java:74)
\n\tat io.fabric8.kubernetes.client.impl.ResourceHandlerImpl.operation(ResourceHandlerImpl.java:81)\n\tat io.fabric8.kubernetes.client.impl.Handlers.getOperation
(Handlers.java:145)\n\tat io.fabric8.kubernetes.client.impl.BaseClient.resources(BaseClient.java:279)\n\tat io.fabric8.kubernetes.client.Client.resources
(Client.java:162)\n\tat io.fabric8.kubernetes.client.impl.KubernetesClientImpl.configMaps(KubernetesClientImpl.java:488)\n\tat 
io.fabric8.kubernetes.client.NamespacedKubernetesClientAdapter.configMaps(NamespacedKubernetesClientAdapter.java:358)\n\tat org.springframework.cloud.kubernetes.fabric8.config.Fabric8ConfigUtils.getConfigMapData(Fabric8ConfigUtils.java:118)\n\tat org.springframework.cloud.kubernetes.fabric8.config.Fabric8ConfigMapPropertySource.getData(Fabric8ConfigMapPropertySource.java:79)\n\tat org.springframework.cloud.kubernetes.fabric8.config.Fabric8ConfigMapPropertySource.<init>(Fabric8ConfigMapPropertySource.java:70)\n\tat org.springframework.cloud.kubernetes.fabric8.config.Fabric8ConfigMapPropertySourceLocator.getMapPropertySource(Fabric8ConfigMapPropertySourceLocator.java:74)\n\tat org.springframework.cloud.kubernetes.commons.config.ConfigMapPropertySourceLocator.getMapPropertySourceForSingleConfigMap(ConfigMapPropertySourceLocator.java:95)\n\tat org.springframework.cloud.kubernetes.commons.config.ConfigMapPropertySourceLocator.lambda$locate$0(ConfigMapPropertySourceLocator.java:75)\n\tat java.base/java.lang.Iterable.forEach(Iterable.java:75)\n\tat org.springframework.cloud.kubernetes.commons.config.ConfigMapPropertySourceLocator.locate(ConfigMapPropertySourceLocator.java:75)\n\tat org.springframework.cloud.bootstrap.config.PropertySourceLocator.locateCollection(PropertySourceLocator.java:51)\n\tat org.springframework.cloud.bootstrap.config.PropertySourceLocator.locateCollection(PropertySourceLocator.java:47)\n\tat org.springframework.cloud.kubernetes.commons.config.ConfigMapPropertySourceLocator.locateCollection(ConfigMapPropertySourceLocator.java:87)\n\tat org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:95)\n\tat org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:607)\n\tat org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:373)\n\tat org.springframework.boot.SpringApplication.run(SpringApplication.java:307)\n\tat org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)\n\tat org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)\n\tat com.ericsson.oss.common.service.ns.NotificationServiceApplication.main(NotificationServiceApplication.java:35)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:566)\n\tat org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)\n\tat org.springframework.boot.loader.Launcher.launch(Launcher.java:107)\n\tat org.springframework.boot.loader.Launcher.launch(Launcher.java:58)\n\tat org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)\nCaused by: java.lang.ClassNotFoundException: io.fabric8.kubernetes.model.jackson.UnmatchedFieldTypeModule\n\tat java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)\n\tat java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)\n\tat org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)\n\tat java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)\n\t... 34 common frames omitted\n","service_id":"eric-oss-notification-service","severity":"error"}
