### ISSUE TITLE
migrating spring boot from 1.5.10 to 2.0.0 met NoSuchMethodError

### ISSUE THREAD

**Issue by fcjxxl** [spring-projects/spring-boot#12566]
According to https://docs.spring.io/spring-security-oauth2-boot/docs/current/reference/htmlsingle/
add dependencies below

```
<dependency> <groupId>org.springframework.boot</groupId> <artifactId>spring-boot-starter-security</artifactId> </dependency>

<dependency> <groupId>org.springframework.security.oauth.boot</groupId> <artifactId>spring-security-oauth2-autoconfigure</artifactId> <version>2.0.0.RELEASE</version> </dependency
```

After migrating spring boot from 1.5.10 to 2.0.0, the spring boot + spring security oauth2 + redis seems has some bug:

```
2018-03-19 11:58:41.650 ERROR 6862 --- [nio-8443-exec-2] o.s.s.o.provider.endpoint.TokenEndpoint : Handling error: NestedServletException, Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: org.springframework.data.redis.connection.RedisConnection.set([B[B)V

org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: org.springframework.data.redis.connection.RedisConnection.set([B[B)V
at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1006) ~[spring-webmvc-5.0.4.RELEASE.jar:5.0.4.RELEASE]
```

this line throws exception:
conn.set(accessKey, serializedAccessToken);
it seems there is no conn.set(…) in the interface RedisConnection, the method needs to change to conn.stringCommands().set(…)

**Comment by wilkinsona** [comment]
It looks like you have an incompatible combination of dependency versions. I can’t tell what that combination is as you haven’t provided enough information. Please provide a small sample that reproduces the problem.

**Comment by fcjxxl** [comment]
After application started, type in command line:

curl -X POST \
  'http://localhost:8080/oauth/token?grant_type=password&username=user_1&password=123456' \
  -H 'Authorization: Basic dXNlcjpzZWNyZXQ='

will reproduce the problem.
[demo1.zip](https://github.com/spring-projects/spring-boot/files/1836108/demo1.zip)

**Comment by lzimd** [comment]
see [spring-security-oauth #1230](https://github.com/spring-projects/spring-security-oauth/issues/1230)

**Comment by wilkinsona** [comment]
Thank you, @lzimd. I've comment on that issue. It is where this problem needs to be solved so I'll close this issue in favour of that one. /cc @rwinch @jgrandja
