### ISSUE TITLE
java.lang.NoSuchMethodError: org.springframework.data.repository.config.AnnotationRepositoryConfigurationSource.<init>

### ISSUE THREAD

**Issue by vladimiril** [spring-projects/spring-boot#9606]
Spring-boot can't be started on SNAPSHOT version.
```
20:50:12.382 [main] INFO  p.d.meeting.SignalServerApplication - Starting SignalServerApplication v0.0.1-SNAPSHOT on isitup.deta.pro with PID 11052 (/opt/ss/signal-server-0.0.1-SNAPSHOT.jar started by gitlab-runner in /opt/ss)
20:50:12.406 [main] DEBUG p.d.meeting.SignalServerApplication - Running with Spring Boot v2.0.0.BUILD-SNAPSHOT, Spring v5.0.0.BUILD-SNAPSHOT
20:50:12.407 [main] INFO  p.d.meeting.SignalServerApplication - The following profiles are active: dev
20:50:13.165 [main] INFO  o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext - Refreshing org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@6f4a47c7: startup date [Mon Jun 26
20:50:13 CEST 2017]; root of context hierarchy
20:50:38.968 [main] INFO  o.s.b.f.s.DefaultListableBeanFactory - Overriding bean definition for bean 'meetingWebSocketHandler' with a different definition: replacing [Generic bean: class [pro.deta.meeting.ws.MeetingWebSocketHandler];
 scope=singleton; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null; defined in URL [ja
r:file:/opt/ss/signal-server-0.0.1-SNAPSHOT.jar!/BOOT-INF/classes!/pro/deta/meeting/ws/MeetingWebSocketHandler.class]] with [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowire
Candidate=true; primary=false; factoryBeanName=webSocketConfiguration; factoryMethodName=meetingWebSocketHandler; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [pro/deta/meeting/configuration/WebSo
cketConfiguration.class]]
20:50:42.329 [main] INFO  o.s.b.f.s.DefaultListableBeanFactory - Overriding bean definition for bean 'httpRequestHandlerAdapter' with a different definition: replacing [Root bean: class [null]; scope=; abstract=false; lazyInit=false;
 autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration$EnableWebMvcConfiguration; factoryMethodName=httpRequestHandlerAdap
ter; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]] with [Root bean: class [null]; scope
=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.data.rest.webmvc.config.RepositoryRestMvcConfiguration; factoryMethodName=httpRequestHan
dlerAdapter; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/data/rest/webmvc/config/RepositoryRestMvcConfiguration.class]]
20:50:43.074 [main] INFO  o.s.b.f.s.DefaultListableBeanFactory - Overriding bean definition for bean 'managementServletContext' with a different definition: replacing [Root bean: class [null]; scope=; abstract=false; lazyInit=false;
autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.boot.actuate.autoconfigure.EndpointWebMvcHypermediaManagementContextConfiguration; factoryMethodName=managementServletConte
xt; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/actuate/autoconfigure/EndpointWebMvcHypermediaManagementContextConfiguration.class]] with [Root bean: class [null]; scope
=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.boot.actuate.autoconfigure.EndpointWebMvcAutoConfiguration; factoryMethodName=management
ServletContext; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/actuate/autoconfigure/EndpointWebMvcAutoConfiguration.class]]
20:50:43.490 [main] ERROR o.s.boot.SpringApplication - Application startup failed 
java.lang.NoSuchMethodError: org.springframework.data.repository.config.AnnotationRepositoryConfigurationSource.<init>(Lorg/springframework/core/type/AnnotationMetadata;Ljava/lang/Class;Lorg/springframework/core/io/ResourceLoader;Lor
g/springframework/core/env/Environment;)V
        at org.springframework.boot.autoconfigure.data.AbstractRepositoryConfigurationSourceSupport$1.<init>(AbstractRepositoryConfigurationSourceSupport.java:68)
        at org.springframework.boot.autoconfigure.data.AbstractRepositoryConfigurationSourceSupport.getConfigurationSource(AbstractRepositoryConfigurationSourceSupport.java:67)
```

**Comment by wilkinsona** [comment]
Please refresh your Spring Boot snapshot. This was fixed in https://github.com/spring-projects/spring-boot/commit/5a4ef50ef1d71f1a42edaee309b3e04fb754b13a.

**Comment by JavaNeed** [comment]
@wilkinsona - I am also facing the exact issue. I have raised the issue here as well https://stackoverflow.com/questions/46138692/java-lang-nosuchmethoderror-org-springframework-data-repository-config-annotati?noredirect=1#comment79239281_46138692, Please guide.

**Comment by samgurtman** [comment]
This is not working in Release 1.5.8 either.

**Comment by wilkinsona** [comment]
@samgurtman 1.5.8 would not have compiled if that were the case by default. You must have some overridden and mismatched dependency versions.

**Comment by cforce** [comment]
Having the same issue as @samgurtman - run dependecy:tree plugin and did not find any overwritten artifact version

**Comment by wilkinsona** [comment]
@cforce Can you provide a sample that illustrates the behaviour you've described? As things stand, we don't understand how the problem you've describe can occur.

**Comment by anvo1115** [comment]
I had the same issue. It was cured by updating org.springframework.data artifacts

            <dependency>
                <groupId>org.springframework.data</groupId>
                <artifactId>spring-data-commons</artifactId>
                <version>1.13.8.RELEASE</version>
            </dependency>

            <dependency>
                <groupId>org.springframework.data</groupId>
                <artifactId>spring-data-jpa</artifactId>
                <version>1.11.8.RELEASE</version>
            </dependency>

            <dependency>
                <groupId>org.springframework.data</groupId>
                <artifactId>spring-data-mongodb</artifactId>
                <version>1.10.8.RELEASE</version>
            </dependency>

**Comment by alvgarvilla** [comment]
Same problem overhere...

```
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.5.8.RELEASE</version>
    </parent>

<dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
</dependencies>
```

**Comment by philwebb** [comment]
@alvgarvilla Can you provide a sample that illustrates the behaviour you've described?

**Comment by EwyynTomato** [comment]
I found out I can reproduce this issue if I add `spring-session-data-redis` as dependency:

```
compile group: 'org.springframework.boot', name: 'spring-boot-starter-web', version: "1.5.11.RELEASE"
compile group: 'org.springframework.boot', name: 'spring-boot-starter-security', version: "1.5.11.RELEASE"
compile group: 'org.springframework.session', name: 'spring-session-data-redis', version: "1.3.2.RELEASE"
```

But all is well after I added `spring-boot-starter-data-jpa`

```
compile group: 'org.springframework.boot', name: 'spring-boot-starter-data-jpa', version: "1.5.11.RELEASE"
```

**Comment by zhangxiaoluan** [comment]
我现在这边也出问题了，不知道如何修改

**Comment by philwebb** [comment]
> I have a problem here, I don’t know how to modify it.

@zhangxiaoluan This issue is closed, if you have found a bug please open a new issue and provide a sample that shows the problem. For questions, please ask on stackoverflow.com.
