### ISSUE TITLE
Java 6 and Tomcat 7.0.63+ throw NoClassDefFoundError

### ISSUE THREAD

**Issue by imgx64** [spring-projects/spring-boot#4846]
Running a `spring-boot-starter-web` project with Java 6 and Tomcat 7.0.63+ (it works fine with Tomcat 7.0.62 and earlier) produces exception `java.lang.ClassNotFoundException: java.nio.charset.StandardCharsets`.

To reproduce, build a Spring Boot application with `spring-boot-starter-web` dependency and the following properties in pom.xml:
```
<java.version>1.6</java.version>
<tomcat.version>7.0.63</tomcat.version>
```

Then **run with Java 6**

Output:
```

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::  (v1.3.2.BUILD-SNAPSHOT)

2015-12-27 08:56:21.584  INFO 34281 --- [           main] com.example.DemoApplication              : Starting DemoApplication on wsdvirgm with PID 34281 (/Users/csdvirg/workspaces/sts-3.7/demo/target/classes started by csdvirg in /Users/csdvirg/workspaces/sts-3.7/demo)
2015-12-27 08:56:21.589  INFO 34281 --- [           main] com.example.DemoApplication              : No active profile set, falling back to default profiles: default
2015-12-27 08:56:21.664  INFO 34281 --- [           main] ationConfigEmbeddedWebApplicationContext : Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@7f42731: startup date [Sun Dec 27 08:56:21 AST 2015]; root of context hierarchy
2015-12-27 08:56:22.363  INFO 34281 --- [           main] o.s.b.f.s.DefaultListableBeanFactory     : Overriding bean definition for bean 'beanNameViewResolver' with a different definition: replacing [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.boot.autoconfigure.web.ErrorMvcAutoConfiguration$WhitelabelErrorViewConfiguration; factoryMethodName=beanNameViewResolver; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/autoconfigure/web/ErrorMvcAutoConfiguration$WhitelabelErrorViewConfiguration.class]] with [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration$WebMvcAutoConfigurationAdapter; factoryMethodName=beanNameViewResolver; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/autoconfigure/web/WebMvcAutoConfiguration$WebMvcAutoConfigurationAdapter.class]]
2015-12-27 08:56:22.878  INFO 34281 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat initialized with port(s): 7080 (http)
2015-12-27 08:56:22.888  INFO 34281 --- [           main] o.apache.catalina.core.StandardService   : Starting service Tomcat
2015-12-27 08:56:22.889  INFO 34281 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/7.0.63
2015-12-27 08:56:23.072  INFO 34281 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2015-12-27 08:56:23.072  INFO 34281 --- [ost-startStop-1] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 1414 ms
2015-12-27 08:56:23.414  INFO 34281 --- [ost-startStop-1] o.s.b.c.e.ServletRegistrationBean        : Mapping servlet: 'dispatcherServlet' to [/]
2015-12-27 08:56:23.416  INFO 34281 --- [ost-startStop-1] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'characterEncodingFilter' to: [/*]
2015-12-27 08:56:23.416  INFO 34281 --- [ost-startStop-1] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2015-12-27 08:56:23.416  INFO 34281 --- [ost-startStop-1] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'httpPutFormContentFilter' to: [/*]
2015-12-27 08:56:23.416  INFO 34281 --- [ost-startStop-1] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'requestContextFilter' to: [/*]
2015-12-27 08:56:23.435 ERROR 34281 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Exception sending context initialized event to listener instance of class org.apache.tomcat.websocket.server.WsContextListener

java.lang.NoClassDefFoundError: java/nio/charset/StandardCharsets
	at org.apache.tomcat.websocket.WsWebSocketContainer.<clinit>(WsWebSocketContainer.java:109) ~[tomcat-embed-websocket-7.0.63.jar:7.0.63]
	at org.apache.tomcat.websocket.server.WsSci.init(WsSci.java:154) ~[tomcat-embed-websocket-7.0.63.jar:7.0.63]
	at org.apache.tomcat.websocket.server.WsContextListener.contextInitialized(WsContextListener.java:39) ~[tomcat-embed-websocket-7.0.63.jar:7.0.63]
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5017) [tomcat-embed-core-7.0.63.jar:7.0.63]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5531) [tomcat-embed-core-7.0.63.jar:7.0.63]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-embed-core-7.0.63.jar:7.0.63]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1574) [tomcat-embed-core-7.0.63.jar:7.0.63]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1564) [tomcat-embed-core-7.0.63.jar:7.0.63]
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303) [na:1.6.0_65]
	at java.util.concurrent.FutureTask.run(FutureTask.java:138) [na:1.6.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895) [na:1.6.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918) [na:1.6.0_65]
	at java.lang.Thread.run(Thread.java:695) [na:1.6.0_65]
Caused by: java.lang.ClassNotFoundException: java.nio.charset.StandardCharsets
	at java.net.URLClassLoader$1.run(URLClassLoader.java:202) ~[na:1.6.0_65]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.6.0_65]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190) ~[na:1.6.0_65]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306) ~[na:1.6.0_65]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301) ~[na:1.6.0_65]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247) ~[na:1.6.0_65]
	... 13 common frames omitted

2015-12-27 08:56:23.435 ERROR 34281 --- [ost-startStop-1] o.apache.catalina.core.StandardContext   : One or more listeners failed to start. Full details will be found in the appropriate container log file
2015-12-27 08:56:23.436 ERROR 34281 --- [ost-startStop-1] o.apache.catalina.core.StandardContext   : Context [] startup failed due to previous errors
2015-12-27 08:56:23.605  INFO 34281 --- [           main] s.w.s.m.m.a.RequestMappingHandlerAdapter : Looking for @ControllerAdvice: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@7f42731: startup date [Sun Dec 27 08:56:21 AST 2015]; root of context hierarchy
2015-12-27 08:56:23.673  INFO 34281 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error]}" onto public org.springframework.http.ResponseEntity<java.util.Map<java.lang.String, java.lang.Object>> org.springframework.boot.autoconfigure.web.BasicErrorController.error(javax.servlet.http.HttpServletRequest)
2015-12-27 08:56:23.674  INFO 34281 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error],produces=[text/html]}" onto public org.springframework.web.servlet.ModelAndView org.springframework.boot.autoconfigure.web.BasicErrorController.errorHtml(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse)
2015-12-27 08:56:23.699  INFO 34281 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/webjars/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2015-12-27 08:56:23.699  INFO 34281 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2015-12-27 08:56:23.761  INFO 34281 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/**/favicon.ico] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2015-12-27 08:56:23.925  INFO 34281 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2015-12-27 08:56:24.002  INFO 34281 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat started on port(s): 7080 (http)
2015-12-27 08:56:24.009  INFO 34281 --- [           main] com.example.DemoApplication              : Started DemoApplication in 2.873 seconds (JVM running for 3.463)
```

**Comment by snicoll** [comment]
Sounds like an issue in Tomcat to me. WDYT @markt-asf?

**Comment by imgx64** [comment]
Standalone Tomcat 7.0.63 works with Java 6 with no problem (by automatically disabling websocket when running under Java 6). And I was able to run the Spring Boot application by excluding `tomcat-embed-websocket`.

I don't know what changed in 7.0.63 that makes websocket jars get loaded when running with Spring Boot.

**Comment by markt-asf** [comment]
Known issue (https://bz.apache.org/bugzilla/show_bug.cgi?id=58658) fixed in 7.0.67? Although the changelog (http://tomcat.apache.org/tomcat-7.0-doc/changelog.html) indicates the problem was introduced in 7.0.66 not 7.0.63. I'd test with 7.0.67 and then see where things stand.

**Comment by snicoll** [comment]
Thanks Marc. @imgx64 please see the Tomcat tracker for more detail on this issue (https://bz.apache.org/bugzilla/show_bug.cgi?id=58658)

**Comment by imgx64** [comment]
@snicoll @markt-asf Please reopen this bug. I still get the same exception with `<tomcat.version>7.0.67</tomcat.version>`. It's probably a different bug (since this bug started with `7.0.63` and the referenced bug started with `7.0.66`). See the output below:
```
$ JAVA_HOME=/Library/Java/JavaVirtualMachines/1.6.0_65-b14-462.jdk/Contents/Home/ java -jar target/demo-0.0.1-SNAPSHOT.jar

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::  (v1.3.2.BUILD-SNAPSHOT)

2015-12-28 07:18:50.962  INFO 1480 --- [           main] com.example.DemoApplication              : Starting DemoApplication v0.0.1-SNAPSHOT on wsdvirgm with PID 1480 (/Users/csdvirg/workspaces/sts-3.7/demo/target/demo-0.0.1-SNAPSHOT.jar started by csdvirg in /Users/csdvirg/workspaces/sts-3.7/demo)
2015-12-28 07:18:50.979  INFO 1480 --- [           main] com.example.DemoApplication              : No active profile set, falling back to default profiles: default
2015-12-28 07:18:51.088  INFO 1480 --- [           main] ationConfigEmbeddedWebApplicationContext : Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@41759d12: startup date [Mon Dec 28 07:18:51 AST 2015]; root of context hierarchy
2015-12-28 07:18:52.033  INFO 1480 --- [           main] o.s.b.f.s.DefaultListableBeanFactory     : Overriding bean definition for bean 'beanNameViewResolver' with a different definition: replacing [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.boot.autoconfigure.web.ErrorMvcAutoConfiguration$WhitelabelErrorViewConfiguration; factoryMethodName=beanNameViewResolver; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/autoconfigure/web/ErrorMvcAutoConfiguration$WhitelabelErrorViewConfiguration.class]] with [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration$WebMvcAutoConfigurationAdapter; factoryMethodName=beanNameViewResolver; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/autoconfigure/web/WebMvcAutoConfiguration$WebMvcAutoConfigurationAdapter.class]]
2015-12-28 07:18:52.734  INFO 1480 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat initialized with port(s): 8080 (http)
2015-12-28 07:18:52.749  INFO 1480 --- [           main] o.apache.catalina.core.StandardService   : Starting service Tomcat
2015-12-28 07:18:52.750  INFO 1480 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/7.0.67
2015-12-28 07:18:53.149  INFO 1480 --- [ost-startStop-1] org.apache.catalina.startup.TldConfig    : At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
2015-12-28 07:18:53.158  INFO 1480 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2015-12-28 07:18:53.158  INFO 1480 --- [ost-startStop-1] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 2082 ms
2015-12-28 07:18:53.536  INFO 1480 --- [ost-startStop-1] o.s.b.c.e.ServletRegistrationBean        : Mapping servlet: 'dispatcherServlet' to [/]
2015-12-28 07:18:53.537  INFO 1480 --- [ost-startStop-1] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'characterEncodingFilter' to: [/*]
2015-12-28 07:18:53.538  INFO 1480 --- [ost-startStop-1] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2015-12-28 07:18:53.538  INFO 1480 --- [ost-startStop-1] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'httpPutFormContentFilter' to: [/*]
2015-12-28 07:18:53.538  INFO 1480 --- [ost-startStop-1] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'requestContextFilter' to: [/*]
2015-12-28 07:18:53.555 ERROR 1480 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Exception sending context initialized event to listener instance of class org.apache.tomcat.websocket.server.WsContextListener

java.lang.NoClassDefFoundError: java/nio/charset/StandardCharsets
        at org.apache.tomcat.websocket.WsWebSocketContainer.<clinit>(WsWebSocketContainer.java:112) ~[tomcat-embed-websocket-7.0.67.jar!/:7.0.67]
        at org.apache.tomcat.websocket.server.WsSci.init(WsSci.java:154) ~[tomcat-embed-websocket-7.0.67.jar!/:7.0.67]
        at org.apache.tomcat.websocket.server.WsContextListener.contextInitialized(WsContextListener.java:39) ~[tomcat-embed-websocket-7.0.67.jar!/:7.0.67]
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5077) [tomcat-embed-core-7.0.67.jar!/:7.0.67]
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5591) [tomcat-embed-core-7.0.67.jar!/:7.0.67]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-embed-core-7.0.67.jar!/:7.0.67]
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1574) [tomcat-embed-core-7.0.67.jar!/:7.0.67]
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1564) [tomcat-embed-core-7.0.67.jar!/:7.0.67]
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303) [na:1.6.0_65]
        at java.util.concurrent.FutureTask.run(FutureTask.java:138) [na:1.6.0_65]
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895) [na:1.6.0_65]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918) [na:1.6.0_65]
        at java.lang.Thread.run(Thread.java:695) [na:1.6.0_65]
Caused by: java.lang.ClassNotFoundException: java.nio.charset.StandardCharsets
        at java.net.URLClassLoader$1.run(URLClassLoader.java:202) ~[na:1.6.0_65]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.6.0_65]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:190) ~[na:1.6.0_65]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:306) ~[na:1.6.0_65]
        at org.springframework.boot.loader.LaunchedURLClassLoader.doLoadClass(LaunchedURLClassLoader.java:178) ~[demo-0.0.1-SNAPSHOT.jar!/:0.0.1-SNAPSHOT]
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:142) ~[demo-0.0.1-SNAPSHOT.jar!/:0.0.1-SNAPSHOT]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:247) ~[na:1.6.0_65]
        ... 13 common frames omitted

2015-12-28 07:18:53.555 ERROR 1480 --- [ost-startStop-1] o.apache.catalina.core.StandardContext   : One or more listeners failed to start. Full details will be found in the appropriate container log file
2015-12-28 07:18:53.559 ERROR 1480 --- [ost-startStop-1] o.apache.catalina.core.StandardContext   : Context [] startup failed due to previous errors
2015-12-28 07:18:53.760  INFO 1480 --- [           main] s.w.s.m.m.a.RequestMappingHandlerAdapter : Looking for @ControllerAdvice: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@41759d12: startup date [Mon Dec 28 07:18:51 AST 2015]; root of context hierarchy
2015-12-28 07:18:53.844  INFO 1480 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error]}" onto public org.springframework.http.ResponseEntity<java.util.Map<java.lang.String, java.lang.Object>> org.springframework.boot.autoconfigure.web.BasicErrorController.error(javax.servlet.http.HttpServletRequest)
2015-12-28 07:18:53.845  INFO 1480 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error],produces=[text/html]}" onto public org.springframework.web.servlet.ModelAndView org.springframework.boot.autoconfigure.web.BasicErrorController.errorHtml(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse)
2015-12-28 07:18:53.873  INFO 1480 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/webjars/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2015-12-28 07:18:53.873  INFO 1480 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2015-12-28 07:18:53.949  INFO 1480 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/**/favicon.ico] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2015-12-28 07:18:54.126  INFO 1480 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2015-12-28 07:18:54.286  INFO 1480 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat started on port(s): 8080 (http)
2015-12-28 07:18:54.290  INFO 1480 --- [           main] com.example.DemoApplication              : Started DemoApplication in 4.108 seconds (JVM running for 4.92)
```

**Comment by snicoll** [comment]
@imgx64 the issue is in Tomcat, not Spring Boot. I gave you the reference already. Feel free to comment on the bugzilla issue unless @markt-asf beats you to it.

**Comment by markt-asf** [comment]
@snicoll You don't appear to have read my comment very carefully, particularly the question mark at the end of the first sentence or the entire of the final sentence.

The OP tested Spring Boot with Tomcat 7.0.67 where BZ 58658 is fixed and still saw the same issue. That is a clear signal that the issues are not the same. Further, if you had compared the stack traces you would have seen notable differences.

That both issues involve Tomcat, WebSocket and Java 6 is not sufficient evidence to conclude that the issues are the same.

Having dug into this a little, this looks like a Spring Boot issue at this point. Spring Boot is unconditionally adding the WsContextListener to the web application which forces WebSocket support to be enabled. WebSocket support requires Java 7 so, unsurprisingly, it fails when the Spring Boot application is running on Java 6.

If Tomcat is left to enable this using the SCI mechanism, the SCI tests for Java 7 or later and only enables WebSocket support when Java 7 or later is available.

The reason this appeared to work on 7.0.62 and earlier is due to https://svn.apache.org/r1682868
Prior to that change, everything would have been fine until the application tried to use WebSocket. After that change the failure happens earlier.

**Comment by snicoll** [comment]
Arg. I haven't seen the question mark and the two stacktraces are completely different. I guess I got caught by the fact that the stack above did not involve Spring Boot _at all_. Thanks for the feedback Mark.
