### ISSUE TITLE
Exception thrown after migrating from M7 to 1.0.0.RC1

### ISSUE THREAD

**Issue by jmirc** [spring-projects/spring-boot#278]
After migrating to 1.0.0.RC1, I got the following exception when I run the application within tomcat.

[WARN] org.springframework.boot.SpringApplication - Error creating bean with name 'org.springframework.scheduling.annotation.SchedulingConfiguration': Initialization of bean failed; nested exception is java.lang.NoSuchMethodError: org.springframework.scheduling.annotation.SchedulingConfiguration.setBeanFactory(Lorg/springframework/beans/factory/BeanFactory;)V)

For your information, I have no issue when the application is started from the command line.

You can have access to the code on Jhipster (https://github.com/jhipster/generator-jhipster).
