### ISSUE TITLE
Annotation processors stop working after 3.5.7 -> 4.0.0-RC1

### ISSUE THREAD

**Issue by OrangeDog** [spring-projects/spring-boot#47853]
I don't really understand how this could happen, and I'm struggling to get any logs to confirm what's going on.

After upgrading my Spring Boot application to 4.0.0-RC1 and adjusting dependencies as directed, none of the annotation processors appear to do anything when compiling.

This causes various compile errors such as `cannot find symbol` for missing Q classes and `@Getter`s on my JPA entities.

```xml
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-compiler-plugin</artifactId>
  <configuration>
    <annotationProcessorPaths>
      <processorPath>
        <groupId>io.github.openfeign.querydsl</groupId>
        <artifactId>querydsl-apt</artifactId>
        <classifier>jpa</classifier>
        <!-- imported from io.github.openfeign.querydsl:querydsl-bom:7.1 (also tried 6.12) -->
      </processorPath>
      <processorPath>
        <groupId>org.projectlombok</groupId>
        <artifactId>lombok</artifactId>
      </processorPath>
      <processorPath>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-autoconfigure-processor</artifactId>
      </processorPath>
      <processorPath>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-configuration-processor</artifactId>
      </processorPath>
    </annotationProcessorPaths>
    <annotationProcessorPathsUseDepMgmt>true</annotationProcessorPathsUseDepMgmt>
    <compilerArgs><arg>-Xlint:all</arg></compilerArgs>
    <parameters>true</parameters>
    <proc>full</proc>
  </configuration>
</plugin>
```

I cannot share the whole project, and don't really know what to look at, so can provide snippets on request.

**Comment by snicoll** [comment]
Thanks for trying the release candidate.

Unfortunately the report isn't actionable. I would recommend to use those processors in a fresh project and then work from there. If you need more support, please share a small sample that we can use to reproduce the problem you've described.

**Comment by OrangeDog** [comment]
Yeah, I figured as much. I'll probably wait for the next RC unless anyone has specific ideas what's causing it.

**Comment by snicoll** [comment]
> I'll probably wait for the next RC

I have no idea what you expect to happen for the next RC. Actually, I am wondering how Spring Boot is involved with this at all. Unfortunately, I can't really figure that out with the information you've shared. The only thing that's remotely related is an upgrade of the Maven Compiler Plugin (again, assuming you are using our parent). We did upgrade it in RC1, but also [in 3.5.7](https://github.com/spring-projects/spring-boot/issues/47539) so that shouldn't be it.

We can't justify having an issue opened with no clear direction. If you can provide a sample that shows Spring Boot is involved, I am happy to take a look at it.

**Comment by OrangeDog** [comment]
Yes, I know and I agree. Perhaps the Hibernate update causes an error somewhere in these classes that is being hidden somehow, or something like that. But I also have other things to do and getting an RC1 to work is not top of the list when it might be as mysteriously fixed later as it is mysteriously broken now.

So yes, close this, but maybe someone else will hit the same problem and find it, or maybe none of us will have to think about it ever again.

**Comment by OrangeDog** [comment]
Just noting the same issue with the 4.0 release. Hopefully will be able to work out why at some point.

**Comment by OrangeDog** [comment]
This is just bizarre. Same versions of `javac`, `maven`, `maven-compiler-plugin`, and `lombok`, and none of the methods that would trigger annotation processing are working. I removed `spring-boot-maven-plugin` from the build in case it modified the environment, and that made no difference.

Even with the default compiler settings, I get the message:

>  Annotation processing is enabled because one or more processors were found on the class path.

But they still don't work, with errors as if `-proc:none`:

> [ERROR] cannot find symbol
  symbol:   method `onMethod_()`
  location: `@interface lombok.Setter`

I haven't reproduced in a new project from scratch.

I have started migrating my main project again, and so far it works after making the minimal changes (mostly missing starters and moved autoconfiguration packages) to build with Boot 4. Presumably if it breaks again as I continue upgrading then I'll have a better idea as to why.

**Comment by snicoll** [comment]
This doesn't seem to be related to Spring Boot. Can you please move this elsewhere?

**Comment by OrangeDog** [comment]
I solved the problem anyway. It was the switch from `org.springframework.lang` to `org.jspecify.annotations`.

The replacement annotation cannot be used in all the same places, but do not generate any error/warning from the compiler.
A different tool, however, gave me these messages:

> Static member qualifying type may not be annotated

To fix, instances of `@NonNull Outer.Inner` must be changed to `Outer.@NonNull Inner`.

> Primitive type members cannot be annotated

To fix, instances of `@NonNull type[]` must be changed to `type @NonNull[]`.

Perhaps a note about this in the [migration guide](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-4.0-Migration-Guide)?

**Comment by wilkinsona** [comment]
Glad to hear that you got to the bottom of it.

The migration from Spring Framework's nullness annotations to JSpecify's is covered in [Spring Framework's release notes](https://github.com/spring-projects/spring-framework/wiki/Spring-Framework-7.0-Release-Notes#null-safety). @sdeleuze, do you think it'd be worth adding something there about JSpecify's annotations being `TYPE_USE` and how that affects their usage?

**Comment by sdeleuze** [comment]
There is a dedicated note about that in https://docs.spring.io/spring-framework/reference/core/null-safety.html#null-safety-migrating which is linked in the release notes, so I tend to think that's good enough, but please let me know if you think we should refine.

**Comment by wilkinsona** [comment]
I agree that's good enough. Thanks, @sdeleuze.

**Comment by OrangeDog** [comment]
That should really be linked from here: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-4.0-Migration-Guide#jspecify-nullability-annotations

I was expecting all the migration information to be in the migration guide, not the release notes.

**Comment by philwebb** [comment]
I've added a link
