### ISSUE TITLE
Jetty 8 not working with 1.2.0.RC1

### ISSUE THREAD

**Issue by cmuchinsky-zz** [spring-projects/spring-boot#1925]
I tried using Jetty 8 with Spring Boot 1.2.0.RC1, but ran into the following issue. It appears the Jetty 8 connector factory is referencing a Jetty 9 class: 

```
Caused by: java.lang.NoClassDefFoundError: org/eclipse/jetty/server/ServerConnector
    at org.springframework.boot.context.embedded.jetty.JettyEmbeddedServletContainerFactory$Jetty8SslServerConnectorFactory.getConnector(JettyEmbeddedServletContainerFactory.java:507)
    at org.springframework.boot.context.embedded.jetty.JettyEmbeddedServletContainerFactory.getEmbeddedServletContainer(JettyEmbeddedServletContainerFactory.java:123)
    at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.createEmbeddedServletContainer(EmbeddedWebApplicationContext.java:148)
    at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:121)
```
