### ISSUE TITLE
Cannot compile custom CRaSH commands running app as a service

### ISSUE THREAD

**Issue by maurocchi** [spring-projects/spring-boot#7471]
In [attachment](https://github.com/spring-projects/spring-boot/files/611064/spring-boot-issue-7471.zip) a sample Spring Boot project to reproduce the problem.

My environment:
* Spring Boot 1.4.2
* JRE Oracle build 1.8.0_111-b14
* OS: Ubuntu 14.04.5 LTS

Steps to reproduce:
* start the application as a service: `MODE=service LOG_FOLDER=/tmp PID_FOLDER=/tmp target/crash-0.0.1-SNAPSHOT.jar start`
* connect to the shell via ssh (password is "password"): `ssh -p 2000 user@localhost`
* execute the `app` command

The shell print the error _Could not compile command_ and in the `/tmp/crash-*.log` you can see:
```
java.io.IOException: Cannot resolve jar:file:.../crash/target/crash-0.0.1-SNAPSHOT.jar!/BOOT-INF/classes
        at org.crsh.util.ZipIterator.create(ZipIterator.java:100)
        at org.crsh.vfs.spi.url.Node._mergeEntries(Node.java:165)
        at org.crsh.vfs.spi.url.Node.mergeEntries(Node.java:142)
        at org.crsh.vfs.spi.url.Node.merge(Node.java:75)
        at org.crsh.vfs.spi.url.URLDriver.merge(URLDriver.java:42)
        at org.crsh.lang.impl.java.ClasspathResolver.<init>(ClasspathResolver.java:49)
        at org.crsh.lang.impl.java.Compiler.compile(Compiler.java:56)
        at org.crsh.lang.impl.java.JavaCompiler.compileCommand(JavaCompiler.java:59)
        at org.crsh.lang.LanguageCommandResolver.resolveCommand(LanguageCommandResolver.java:128)
        at org.crsh.lang.LanguageCommandResolver.resolveCommand2(LanguageCommandResolver.java:109)
        at org.crsh.lang.LanguageCommandResolver.resolveCommand(LanguageCommandResolver.java:100)
        at org.crsh.shell.impl.command.CRaSH.getCommand(CRaSH.java:100)
        at org.crsh.shell.impl.command.CRaSHSession.getCommand(CRaSHSession.java:96)
        at org.crsh.lang.impl.script.PipeLineFactory.create(PipeLineFactory.java:89)
        at org.crsh.lang.impl.script.ScriptRepl.eval(ScriptRepl.java:88)
        at org.crsh.shell.impl.command.CRaSHSession.createProcess(CRaSHSession.java:163)
        at org.crsh.shell.impl.async.AsyncProcess.execute(AsyncProcess.java:172)
        at org.crsh.console.Console.iterate(Console.java:219)
        at org.crsh.console.Console.on(Console.java:158)
        at org.crsh.console.Console.on(Console.java:135)
        at org.crsh.console.jline.JLineProcessor.run(JLineProcessor.java:204)
        at org.crsh.ssh.term.CRaSHCommand.run(CRaSHCommand.java:99)
        at java.lang.Thread.run(Thread.java:745)
2016-11-24 11:26:18.266 ERROR 8801 --- [pool-1-thread-1] o.crsh.shell.impl.command.CRaSHSession   : Error while evaluating request 'app' Could not compile command

org.crsh.shell.impl.command.spi.CommandException: Could not compile command
        at org.crsh.lang.impl.java.JavaCompiler.compileCommand(JavaCompiler.java:65) ~[crash.shell-1.3.2.jar!/:na]
        at org.crsh.lang.LanguageCommandResolver.resolveCommand(LanguageCommandResolver.java:128) ~[crash.shell-1.3.2.jar!/:na]
        at org.crsh.lang.LanguageCommandResolver.resolveCommand2(LanguageCommandResolver.java:109) ~[crash.shell-1.3.2.jar!/:na]
        at org.crsh.lang.LanguageCommandResolver.resolveCommand(LanguageCommandResolver.java:100) ~[crash.shell-1.3.2.jar!/:na]
        at org.crsh.shell.impl.command.CRaSH.getCommand(CRaSH.java:100) ~[crash.shell-1.3.2.jar!/:na]
        at org.crsh.shell.impl.command.CRaSHSession.getCommand(CRaSHSession.java:96) ~[crash.shell-1.3.2.jar!/:na]
        at org.crsh.lang.impl.script.PipeLineFactory.create(PipeLineFactory.java:89) ~[crash.shell-1.3.2.jar!/:na]
        at org.crsh.lang.impl.script.ScriptRepl.eval(ScriptRepl.java:88) ~[crash.shell-1.3.2.jar!/:na]
        at org.crsh.shell.impl.command.CRaSHSession.createProcess(CRaSHSession.java:163) ~[crash.shell-1.3.2.jar!/:na]
        at org.crsh.shell.impl.async.AsyncProcess.execute(AsyncProcess.java:172) ~[crash.shell-1.3.2.jar!/:na]
        at org.crsh.console.Console.iterate(Console.java:219) ~[crash.shell-1.3.2.jar!/:na]
        at org.crsh.console.Console.on(Console.java:158) ~[crash.shell-1.3.2.jar!/:na]
        at org.crsh.console.Console.on(Console.java:135) ~[crash.shell-1.3.2.jar!/:na]
        at org.crsh.console.jline.JLineProcessor.run(JLineProcessor.java:204) ~[crash.shell-1.3.2.jar!/:na]
        at org.crsh.ssh.term.CRaSHCommand.run(CRaSHCommand.java:99) ~[crash.connectors.ssh-1.3.2.jar!/:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
Caused by: org.crsh.lang.impl.java.CompilationFailureException: package org.crsh.cli does not exist
package org.crsh.command does not exist
cannot find symbol
  symbol: class BaseCommand
cannot find symbol
  symbol:   class Command
  location: class app

        at org.crsh.lang.impl.java.Compiler.compile(Compiler.java:81) ~[crash.shell-1.3.2.jar!/:na]
        at org.crsh.lang.impl.java.JavaCompiler.compileCommand(JavaCompiler.java:59) ~[crash.shell-1.3.2.jar!/:na]
        ... 15 common frames omitted
```

It could be related to #6384.

**Comment by wilkinsona** [comment]
Thanks for the sample. The problem can also be reproduced by using `java -jar` directly, i.e. there's no need to run the app in service mode. This is related to #6384 but it's not the same problem. Interestingly, your sample works fine with Spring Boot 1.4.1 so something's changed in 1.4.2 that's broken this.

**Comment by wilkinsona** [comment]
The change in behaviour is a side-effect of https://github.com/spring-projects/spring-boot/issues/7003. The change made in that issue means that CRaSH should now be able to look in `BOOT-INF/classes` when compiling a command but, thanks to the naive way in which it works with jar files, it doesn't work. In fact, not only does it not manage to look in `BOOT-INF/classes`, the failure when it attempts to do so leaves CRaSH's compiler with an empty classpath.

**Comment by wilkinsona** [comment]
The quickest and easiest way to avoid the problem is to rename `app.java` to `app.groovy`. This causes CRaSH to use its `GroovyCompiler` which doesn't rely on the same brittle logic to search for classes to compile against.

To get `.java` commands to work, we need to replace CRaSH's `JavaCompiler` with our own implementation that can find class files more robustly. Doing so seems to require about 300 lines of code. Given that CRaSH is deprecated in 1.5 and will be removed in 2.0 I am not sure that it's worth it.

**Comment by maurocchi** [comment]
I've just started using it and now I discover that CRaSH will be deprecated in future releases!
Anyway thanks for the explanation.

**Comment by bric3** [comment]
The issue is a bit old, but since we had this issue as well, I published a quick fix resolving this issue in (https://github.com/crashub/crash/pull/119).

It might be worth investigating https://github.com/corda/crash fork as well.
